### ISSUE TITLE
Feature suggestion: Copy/paste feature for workout segments

### ISSUE THREAD

**Issue by Jo11n** [svenmeier/coxswain#1]
Great app! It'd be great if one could copy/cut/paste workout segments in the editor. Editing workouts is a bit tedious at the moment. Suggested behavior: Long press on segment opens copy/cut/paste dialog in the top row of the screen. Ideally, several segments could be selected with check boxes at the same time.

**Comment by svenmeier** [comment]
Thanks for your feedback!

I agree, segment editing can be improved. Selection with long press seems like a good idea.

**Comment by svenmeier** [comment]
This has already been improved, segments can now be reordered and duplicated.
