### ISSUE TITLE
Pause/Continue Workout

### ISSUE THREAD

**Issue by svenmeier** [svenmeier/coxswain#10]
It would be nice to be able to pause a workout. I'll have to investigate how to support this.

**Comment by svenmeier** [comment]
As of now this feature is too difficult to integrate while the gain is questionable.

Perhaps this is easier later on, so I'm postponing this issue.

**Comment by sonytheoao** [comment]
I see you've closed this issue but this feature would be the #1 request I would have for this app.  About 40% of the time, I get interrupted during my workout and particularly during interval or pyramid training, stopping the workout without pausing hoses the stats.  Is there a way to limit pauses for just those workouts with a duration set?

**Comment by svenmeier** [comment]
Actually since #36 Coxswain supports pausing of a workout via the "Hold" button on the Waterrower S4.
Have you tried that?

**Comment by sonytheoao** [comment]
No I was unaware. Thanks for the clarification.
