### ISSUE TITLE
Manual?

### ISSUE THREAD

**Issue by jbkellyjr** [svenmeier/coxswain#104]
Is there a manual for Coxswain somewhere?  For example, I see options to export and have read that I can add workouts to my calendar but I don't know how any of those functions work.

**Comment by inonoob** [comment]
Hey @jbkellyjr 

I've started to create the manual for coxswain. Please check the wiki page of Coxswain. I try to get in contact with Sven in order to get some more information on some points I don't know the function of. 

best regards

**Comment by inonoob** [comment]
Is now available. Please check the wiki
