### ISSUE TITLE
Export to google fit failed

### ISSUE THREAD

**Issue by mns8** [svenmeier/coxswain#105]
Seems to not work at all - installed app on 05/05/2020

**Comment by svenmeier** [comment]
Please try a second time. You have to grant permissions to access Google fit first.

If this doesn't work - what error message is displayed?

**Comment by mns8** [comment]
Hi,

I have granted permissions, I get the message that it is syncing, but then
a message saying the sync to google fit failed and no data in google fit.
Tried to sync multiple times, no luck.

Thanks,

Mark..

**Comment by svenmeier** [comment]
I've reimplemented the export with the latest Google Fit API, so hopefully this will work with the next Coxswain version 7.1
