### ISSUE TITLE
Google Fit Sync issues

### ISSUE THREAD

**Issue by pariahnihililist** [svenmeier/coxswain#107]
Hi,

Excellent app. I am just having issues syncing the workout stats to google fit. The data was seemingly exported successfully through the coxswain app but somehow the Stats (distance and calories) did not follow through. The duration of workout, time and date seems right.

Anyway to resolve this? Thanks!!

**Comment by svenmeier** [comment]
Hi,
are you using version 7.1 already? I updated the Google Fit integration a few days ago.

If yes, try removing access for Coxswain to your account data: https://myaccount.google.com/permissions
A following export in Coxswain should trigger a permission dialog.

**Comment by pariahnihililist** [comment]
Thanks. I am on version 7.1 already. 

Had done as you have suggested to remove access for coxswain but it did not trigger the permission dialog. Will try to export again tomorrow after a new workout and report back. Thanks for your prompt assistance!

**Comment by pariahnihililist** [comment]
Hi, when I tried again, the export failed.

I then deleted the coxswain app and reinstalled and it seems to work fine now with all data syncing. Thanks once again!

**Comment by svenmeier** [comment]
Strange, a reinstall should make no difference.
I'll keep this in mind when others run into this.

**Comment by manukall** [comment]
Hi @svenmeier,
I'm running into the same issue. Reinstalling the app didn't help and on the page you linked to I don't see Coxswain listed at all. 

The export used to work on my old phone, but since I got a new one I get the "Export to Google Fit failed" error message. On that new phone I wasn't asked to give permission.

I have no idea how to debug this, but I've got general programming knowledge. If you can give me some guidance, I'll do what I can...

**Comment by svenmeier** [comment]
@manukall I've just pushed version 7.7 into the play store.
In the settings you'll find a new item "export application log" - hopefully this will result in a file "/coxswain/waterrower.log" being written.
Please initiate a new export into Google Fit, then "export the application log" and attach the file here. Thanks.

**Comment by manukall** [comment]
@svenmeier Awesome, thanks. I've attached the log.

[waterrower.log](https://github.com/svenmeier/coxswain/files/5588729/waterrower.log)

**Comment by svenmeier** [comment]
`com.google.android.gms.common.api.ApiException: 4: The user must be signed in to make this API call.`

Strange, Coxswain asks for the permissions first o_O

You do start the export from the workout context menu "...", right?

**Comment by manukall** [comment]
Yes, I start the export from the workout context menu. I click "Export" then "Google Fit". Then I see that bubble at the bottom saying "Exporting to Google Fit" and after a few seconds it says "Export to Google Fit failed".

**Comment by vonloxley** [comment]
In Google Fit App:
* Are you connected? (It will offer you to disconnect if you klick on the upper right item.)
* Is Coxswain listed as an connected app? (Profile->Settings->Connected Apps)

**Comment by manukall** [comment]
@vonloxley What's the difference between the two? In Google Fit at the top right I see the icon that represents my Google account. If I go to "Profile", "Settings", "Manage connected apps", I don't see Coxswain. Even after switching to "All apps & devices".

**Comment by svenmeier** [comment]
![Screenshot_20201124-160245](https://user-images.githubusercontent.com/543253/100111843-d9c86000-2e6e-11eb-9535-0410e5b83d54.jpg)
![Screenshot_20201124-160236](https://user-images.githubusercontent.com/543253/100111850-db922380-2e6e-11eb-9e41-039fd67225a4.jpg)
You should get a security warning where you can approve the access to Google Fit.

**Comment by svenmeier** [comment]
When I remove Coxswain from the allowed apps, the next export triggers the permission dialog once again.

**Comment by manukall** [comment]
I don't get any of those. I've checked all of my Google accounts, too. Coxswain isn't in the allowed apps for any of them. I don't remember if I removed it at some point.

**Comment by svenmeier** [comment]
After some back-and-forth with the [permission settings](https://myaccount.google.com/permissions) and allowing/revoking access for Coxswain I arrived at the same situation: my exports fail now too :(

I will fix that with a new version.

**Comment by svenmeier** [comment]
Fixed with version 7.8

**Comment by manukall** [comment]
Awesome. I just tried and can confirm it's working. Thanks!
