### ISSUE TITLE
intermittent freezing on bluetooth between transitions

### ISSUE THREAD

**Issue by mryckman** [svenmeier/coxswain#109]
I've had this happen a few times now since switching to Bluetooth from USB. When a workout transitions between phases, at 1 second remaining, the workout locks and stops advancing. The speed and stroke rate continue updating, but the rest of the workout appears to "lock". This has happened twice, each time on new workout plans. When I restarted one of them, it continued through and didn't lock that time. Sorry this is a messy report - that's all I really know.

**Comment by svenmeier** [comment]
What do you mean by 'intermittent'? Does the workout continue after some time or is it advancing again after some time?

Could you please enable "Write trace" in Coxswain's settings and attach the file "coxswain/waterrower.trace" after another row?

**Comment by mryckman** [comment]
Yeah sorry - on the intermittency - I just mean it's happened twice now, but it doesn't happen on every row. I haven't done many rows, and so I don't know if this is useful, but the only pattern I've noticed is that it has only happened after I created a new workout routine. 

Here's a trace file... I'm new to these, and so I'm not sure what I'm looking at exactly. But hopefully it helps. The device is a Pixel 3a

[waterrower.trace.txt](https://github.com/svenmeier/coxswain/files/4714180/waterrower.trace.txt)

**Comment by svenmeier** [comment]
Waterrower has released two different ComModules actually:
Regretfully yours with software-revision 1.30 is the one which reports erroneous time readings. Are you by chance from Australia? I've got a similar report from another user from there.

Would you be so kind and send me pictures of your module to sven@meiers.net ?
I'm not sure how to identify the version from the outside, but I would like to give people the possibility to check by themselves.
Supported devices should have software version 4.1 and up. I was in contact with the Waterrower devs for a fix to the old version, but to no avail.

I'm inclined to add a (yet another) workout to Coxswain, but currently your device is not supported :/.

For now I'd recommend you to return your module, if possible.

**Comment by svenmeier** [comment]
Version 7.2 has a workaround for wrong time readings reported by the ComModule 1.x
