### ISSUE TITLE
How to get the bluetooth module working with coxswain

### ISSUE THREAD

**Issue by inonoob** [svenmeier/coxswain#110]
Hey all,

Request: I'm looking for someone who has the Bluetooth comm module and use it with the coxswain app. Is it possible to explain step by step how to pair the Waterrower and get it working with Coxswain. 

Background: I've created in the wiki section a Coxswain user guide. But I'm using the USB-OTG method to connect to the Waterrower. So I would like to complete the user guide with this missing part. 

Best regards

**Comment by JoernT** [comment]
* Start Coxswain
* hit bluetooth button in top right
* select device from list - you should hear a sound and get a notification saying that Coxswain is connected
* choose a training program by tapping on it
* switch on the S4 device and hit 'ok' button. 
* start rowing

**Comment by inonoob** [comment]
Thank You @JoernT
