### ISSUE TITLE
Folder Structur for Programs

### ISSUE THREAD

**Issue by inonoob** [svenmeier/coxswain#111]
Hey

I'm currently doing the [Beginner Pete Plan](https://thepeteplan.wordpress.com/beginner-training/) I have a lot of program which makes it difficult to find the correct one. 

Request for enhancement: 
- is it possible to be able to move the program to re-arrange them
- additionally would it possible to add an folder structure to also organize them. e.g Hiit trainings, Long and steady trainings. 

Best Regards

**Comment by svenmeier** [comment]
The next version will sort programs by their name.
Not a real folder structure, but you can organize them with your own naming scheme.
