### ISSUE TITLE
Import/Export galaxy S9

### ISSUE THREAD

**Issue by Nikomer** [svenmeier/coxswain#112]
On galaxy S9 (android), with storage allowed.
Failed to export program or import a random TCX : 
# Export : 
message "Exporting program failed" (same with "share...")
# Import
Same message when importing a random TCX

=> I checked there is no "coxswain" directory on the principal storage, created by default

I get the last coxswain version on google play.

**Comment by inonoob** [comment]
Hey Nikomer, 

might you give some more info. 
- What Android version is installed on the S9 ? 
- Do you use a Custom Rom ? 
- Has the Coxswain folder been created ? ==> No 
This is the problem. 

I would propose 2 solution: 
- Check again the permission. I had it one time 
- Try to create a folder called "coxswain" 
- if you have a custom rom check that the file manager can access it. I had this issue with one custom rom which hadn't any file manager which worked with coxswain. I had to install on from F-droid 

But it really sounds like a permission problem.

**Comment by Nikomer** [comment]
Hey,

- Android V10
- Yes external SD ( I have enough free space on both)
- I didn't found any croxswain directory (principal storage, sd)

Permission checked. Then uninstall - install, the os asks for permission that I allow => still failled. Alternatively I installed on galaxy tabs (old version) works like a charm.
Create a directory coxswain, root of my principal storage => still failed
Create a directory coxswain, root of the sd card => still failled

Any time you need tests.

I haven't my WR yet (I had a C2), I will have it at the begging of november, looking foward to test your application which seems just amazing. I'm building my program on my TABs for now.

niko

**Comment by inonoob** [comment]
Hey Niko, 

might we test the following. Can you install version 4.6 of coxswain from github. And retry. Re-install version 4.7 of coxswain. 
Let's check to be sure it has nothing to do with the coxswain versions. 

Best regards

**Comment by Nikomer** [comment]
Hey,

With pleasure, I didn't find the version you mentioned. The versions come from 5.6 to 7.3. 
Anyway, I took the oldest one 5.6.
Works fine. Export the file and re-import it works for me.

Niko

**Comment by Nikomer** [comment]
Please ask If you have a doubt between two versions I can try the before/after version.
Send me the link of the apk because I'm not sure wee are talking about the same version (github/apk)?

Niko

**Comment by inonoob** [comment]
Hey

you are right sorry 4.7 was wrong :). Doesn't exit :) 7.3 is the last version as of today.
May you explain the steps you took. Does it now work with 7.3.

**Comment by Nikomer** [comment]
Installed

5.6 => works
7.2 => works
7.3 (for apk or play store) => failed

Niko

**Comment by inonoob** [comment]
Oki Strange. Maybe ask Sven what did he updated. Something was with updated to API29. 

Maybe something there broke version 7.3

**Comment by Nikomer** [comment]
If you need me to test a new release on Galaxy S9 : just ask.

Niko

**Comment by svenmeier** [comment]
Yes, there seem to be new restrictions with file access on Android 10 (Coxswain is now targeting API 29).
Strangely it works on my own device.

I'll investigate and publish a fix soon.

**Comment by inonoob** [comment]
Hey 

I can confirm on my device it is also working. Oneplus product.

**Comment by svenmeier** [comment]
@Nikomer please try with new version 7.4, this should work now

**Comment by Nikomer** [comment]
@svenmeier,
Tested, works fine now. Directory creation and file export.
Good Job.

**Comment by inonoob** [comment]
@Nikomer Many thanks for the feedback and testing !
