### ISSUE TITLE
Personal record

### ISSUE THREAD

**Issue by Nikomer** [svenmeier/coxswain#113]
Hello Sven,

May I send you these user stories

US1 : As a motivated user I would like to have my personal record store for each workout in terms of distance and/or time, this to keep motivation and store references.
Such as : 
Workout : 10.000m (pr : 45:28:16)
Workout: 1hour (pr : 12345m)
Workout: whatever (pr 24:02:12 / 4567m)

US2 (depending of US1): As a motivated user I would like to have the possibility to choose challenge personal record of the chossen workout (like the workout challenge)

Niko

**Comment by svenmeier** [comment]
Regarding US1::
Next version will filter the workouts by the currently selected program (the performance tab already does this).
Then you can sort them as you need.

**Comment by svenmeier** [comment]
Regarding US2:
If I understand you correctly that will be possible then. Just look up the workout by sorting - e.g. by duration - and then choose challenge from the menu.

**Comment by Nikomer** [comment]
Great, look forward the next version. Great job Sven.
