### ISSUE TITLE
More intensity levels.

### ISSUE THREAD

**Issue by Nikomer** [svenmeier/coxswain#114]
Hello Sven,

I have this US, which is in very low priority but i can be useful for some

US : As a user I would like to have the possibility to add more than 3 intensity levels when I set up a program workout. It could be useful to set up program base on erg heart zone (ut2 ut1 at tr an) or using garmin heart zone (5 zones) for exemple.
So could be 3,4 or 5 zones of intensity. (I know that it mix intensity vs heart zone...)

Best regards, Niko

**Comment by svenmeier** [comment]
Next version will support two additional difficulties "rest" (blue) and "brutal" (red).
