### ISSUE TITLE
Coxswain don't recognized pauses within HIIT training 

### ISSUE THREAD

**Issue by inonoob** [svenmeier/coxswain#116]
After uploading my HIIT trainings to Garmin connect, I saw that during the pause phases with no movement of the rower power, strokeRatio, strokeRate, speed and energy were not 0. 

Problem:  Coxswain don't set power, strokeRatio, strokeRate, speed and energy to 0 during a workout if rower is stopped. 

Root cause: 
After search the Waterrower specification and also check the waterrower.trace of a example hiit training. I found the following. 

The Waterrower doesn't tell if the rower is stop.  
_"XX is an ACH value representing the number of pulse's counted during the last 25mS period; this value can range from 1 to 50 typically. (Zero values will not be transmitted)_
( Water Rower S4 S5 USB Protocol Iss 1 04.pdf /page 8) 

And here is the problem, how is Coxswain suppose to know if the rower is still turning or not. ( See waterrower.trace extract below) 

Proposed solution: 

if after a "<P01" (which is tick close to stop) + 25 lines of stdout no new "<P0X" is seen then the rower must be at stop. And therefore set  power, strokeRatio, strokeRate, speed and energy to 0. Coxswain will then check for the next signal to start counting again. 

   7495 <IDT1E1000054
   7496 <P01
   7497 #unrecognized
   7498 >IRD140
   7499 <IDD140000F
   7500 >IRD057
   7501 <IDD057006C
   7502 <P01
   7503 #unrecognized
   7504 >IRD14A
   7505 <IDD14A008E
   7506 >IRS1A9
   7507 <IDS1A91D
   7508 >IRS1A0
   7509 <IDS1A000
   7510 <P01
   7511 #unrecognized
   7512 >IRD088
   7513 <IDD0880000
   7514 >IRT08A
   7515 <IDT08A000C68
   7516 >IRS1E0
   7517 <IDS1E001
   7518 >IRT1E1
   7519 <IDT1E1000055
   7520 >IRD140
   7521 <P01    <================ Last P01 before complete halt of the rower
   7522 #unrecognized
   7523 <IDD140000F
   7524 >IRD057
   7525 <IDD057006C
   7526 >IRD14A
   7527 <IDD14A008E
   7528 >IRS1A9
   7529 <IDS1A91D
   7530 >IRS1A0
   7531 <IDS1A000
   7532 >IRD088

**Comment by svenmeier** [comment]
It seems to me we can use the PING notification as an indication on when the rower is idle and the values should be reset.
From the specification:
  "Sent once a second while NO rowing is occurring to indicate to the PC the rowing monitor
   is still operational but stopped."

I will test what happens if we reset values on the first PING and ignore following values until the last PING is more than 2 seconds in the past.

**Comment by inonoob** [comment]
That is even better and clever :)

**Comment by svenmeier** [comment]
Version 7.6 fixes this.
