### ISSUE TITLE
Relay bluetooth comm module or emulate it 

### ISSUE THREAD

**Issue by inonoob** [svenmeier/coxswain#118]
I love the coxswain app and to track all my workouts. But I also would like to try and use Kinomap or Zwift at the same time. 

The idea would be the following: 
Case wired: 
if you connect your phone with an otg-usb cable to your smartphone in order to use coxswain and at the same time coxswain would emulate the Bluetooth signal to be sent to a Tablet which is running KINOMAP. I would have Coxswain still tracking everything and I could use KINOMAP to row.

Waterrower => usb-otg=>smartphone=>coxswain=>emulate com module coxswain => Bluetooth => tablet=> Kinomap 

Case Bluetooth comm module: 
Waterrower is connected via Bluetooth comm module to the smartphone and coxswain. Coxswain passthrough those information to a tablet connected via bluetooth and create a second virtual comm module so KINO map 

Waterrower => Bluetooth =>smartphone=>coxswain=>emulate com module coxswain => Bluetooth => tablet=> Kinomap 

Request: emulate the protocol of the comm module with the data stream, create a virtual comm module to send information to a Bluetooth connected tablet to use e.g KINOMAP. 

best Regards

**Comment by svenmeier** [comment]
Thank you very much for your request.
I wasn't aware of Kinomap, that's a really great offering.

However the proposed enhancement is not something I'm planning to add to Coxswain: This will take a considerable amount of time to implement, which I can't invest at the moment.

Closing as won't-do.
