### ISSUE TITLE
Heart rate by Samsung Watch or Samsung health app

### ISSUE THREAD

**Issue by Ppires123123** [svenmeier/coxswain#119]
Hi, thanks for this amazing app.

It would be possible to connect and read heart rate by Samsung Watch or Samsung health app?

Thanks

**Comment by svenmeier** [comment]
Hi,

regretfully there is no clear information on how to read heart rate data from a samsung watch:

https://stackoverflow.com/questions/25712968/how-to-access-galaxy-s5-heart-rate-sensor
https://stackoverflow.com/questions/33844305/samsung-gear-s-continuous-heart-rate-monitoring

If you choose 'Sensor' for heart rate in the Coxswain's settings, the app will try to read from attached body sensors. Regretfully I don't have any other solution, if this doesn't work on your device.

**Comment by Ppires123123** [comment]
Unfortunately don't work. The "sensor" doesn't find it. Thanks for you try. In this moment i'm use the "health Sync" app to sincronize data from heart rate of "samsung health" app to "Google fit" during workout as well "coxswain".

**Comment by svenmeier** [comment]
To bad. Samsung makes it unnecessary hard.
