### ISSUE TITLE
Challenge workout are not tagged

### ISSUE THREAD

**Issue by Nikomer** [svenmeier/coxswain#123]
Hello,

When we challenge a workout, the current workout is not tagged with the name of the challenged workout.
So we are not able to filter all workouts et challenged workout in the same list.

Thanks, Niko

**Comment by svenmeier** [comment]
You have *repeat* the workout (choose repeat instead of challenge from the menu).

I can't remember why I made this distinction, but *repeat* keeps the reference to the original program.

**Comment by Nikomer** [comment]
Ok, thank you.

**Comment by Nikomer** [comment]
Tested today works fine! Thank you very much!
