### ISSUE TITLE
Cannot export more than one entry to Google fit per day?

### ISSUE THREAD

**Issue by zyrorl** [svenmeier/coxswain#124]
Hi there,

I've connected coxswain and given permissions to Google fit and it appears thr first workout exported fine but another workout on the same day won't export for some reason.

Is this a known issue?

**Comment by svenmeier** [comment]
I'm not aware of such an issue.

Are you exporting manually (via the workout menu) or automatically, i.e. have you configured automatic export in the preferences?

**Comment by svenmeier** [comment]
Please retry with the new App version. For me several exports work just fine, note that others have reportedveneral problems with the export to Google Fit.
