### ISSUE TITLE
Make documentation editable for everyone

### ISSUE THREAD

**Issue by lioman** [svenmeier/coxswain#126]
The wiki is only editable for contributors. As a coxswain user I want to fix errors in documentation or enrich it with hints.

There are two solutions: 

1. make github wiki editable for everyone
2. create a documentation with something like mkdocs and publish the documentation as github pages

**Comment by svenmeier** [comment]
Hi, thanks for wanting to contribute!

How about this workflow?

https://gist.github.com/larrybotha/10650410

**Comment by lioman** [comment]
This seems for me a bit complicated, especially  for non coders. To change a typo or clarify  a sentence this is too much. Better would be a ribbon on the edge of a published documentation ' edit on GitHub '  and you can click on it hit the small pencil icon and change the documentation right away.
This is way easier for small changes.

**Comment by svenmeier** [comment]
Sure, it's a complicated process.

Keep in mind that you're only the second person to volunteer to contribute. Let's keep it simple as long as it stays this way.
Should we attract several more contributors, I will revisit you suggestion to an alternative documentation process.

**Comment by JPRAGO** [comment]
Hi,
I can contribute. There is small explanations an précisions that would be welcome in the text.
 I can translate in french the application and the wiki. For application is there à file with translate chains ?

**Comment by svenmeier** [comment]
Many thanks @JPRAGO for chiming in.
For now I've added you to the collaborators, feel free to improve the user guide.

A french translation of the App would be nice too - do you know how to create pull-requests?

**Comment by JPRAGO** [comment]
Hi Sven

I added some précison for creating a new program. Please correct my
english...
I have no expérience with pull-requests but it seems not difficult. I made
a translation using a file containing a translation of chains of
characters. A file by language. So it's very easy to maintain.
I wait your instructions.
Regards
Jean-Paul

Visitez www.imagesde.fr

**Comment by JPRAGO** [comment]
Hi Sven,

The file containing chains to translate is :
coxswain <https://github.com/svenmeier/coxswain>/app
<https://github.com/svenmeier/coxswain/tree/master/app>/src
<https://github.com/svenmeier/coxswain/tree/master/app/src>/main
<https://github.com/svenmeier/coxswain/tree/master/app/src/main>/res
<https://github.com/svenmeier/coxswain/tree/master/app/src/main/res>/values
<https://github.com/svenmeier/coxswain/tree/master/app/src/main/res/values>/
strings.xml
I see there is a values-de.
 Is it possible you create a
coxswain <https://github.com/svenmeier/coxswain>/app
<https://github.com/svenmeier/coxswain/tree/master/app>/src
<https://github.com/svenmeier/coxswain/tree/master/app/src>/main
<https://github.com/svenmeier/coxswain/tree/master/app/src/main>/res
<https://github.com/svenmeier/coxswain/tree/master/app/src/main/res>/values
<https://github.com/svenmeier/coxswain/tree/master/app/src/main/res/values>
-fr/strings.xml
Then I will translate directly in the file.

Or I can download the file and work on it. When I finish I transfer to you
the new file.

Jean-Paul


Visitez www.imagesde.fr

**Comment by svenmeier** [comment]
I created the french translation file. It's probably more convenient to download it, edit it offline and then send it to me.
Or I will guide you through the proper process, i.e. with a pull request.

**Comment by JPRAGO** [comment]
I download the file and begin to edit it offline. I 'll send it to you in a
few days.
After you put the file in line I could make little ajustements in Github.
After that we had to translate help !!


Visitez www.imagesde.fr

**Comment by JPRAGO** [comment]
Hi Swen,

I made the french version. Attached file.
I think it would be a very good thing to test a french version and see if
there are problems in translation. Is it possible for you to compile a
french version and send me apk ?.
If there is modification I will do it online.
When finished I'll inform you.

Suggestion : it's not very intuitive to use hold on S4 to pause a program.
Do you think you can add a button on the program page ? Maybe  a button to
end the program  ?
Google Fit : On my device (Nexus 7) export to Google Fit failed too
(Android 5.1).

Jean-Paul

Visitez www.imagesde.fr

**Comment by JPRAGO** [comment]
I found some mistakes in the first file. New file attached.


Visitez www.imagesde.fr

**Comment by svenmeier** [comment]
Please send the file to sven@meiers.net, your attachment is not accepted by Github.

**Comment by svenmeier** [comment]
Many thanks @JPRAGO , I've added your translation to the new App version. We can easily fix any errors in future versions. Note that I had to abbreviate "Dépense énergétique" since it was to long for some display locations.

**Comment by JPRAGO** [comment]
Hi Swen,

Thank you.
I download 8.6 and install it. I go to my Waterrower to test.
If any problem with traduction I'll make changes in Github.
The problem with french, is the length of chains which are générally longer
than english. So we can use "Energie".
Regards
Jean-Paul

Visitez www.imagesde.fr

**Comment by JPRAGO** [comment]
Hi Sven,

There is a BUG  !!
I try on 2 machines.
When the machine detects S4 it connects it. Immédiatly Cowwsain close.
If I open first Coxswan the program don't work. The window Sensor don't
open and nothing happens when you begin to row.
There is something which seem unusual  on the program, speed is 0,00
Jean-Paul

Visitez www.imagesde.fr

**Comment by svenmeier** [comment]
Please activate "export log" in the Coxswain settings and attach the file /coxswain/app.log to a new issue. Thanks

**Comment by JPRAGO** [comment]
I desinstall  and I install using Paly Store and it work. I test the second
machine and I comme back to you.

Visitez www.imagesde.fr

**Comment by JPRAGO** [comment]
I desinstall the apk I download early on the second machine. I install with
Play. It work !
The export to Google Fit work.
Thank you.
Jean-Paul
Visitez www.imagesde.fr

**Comment by JPRAGO** [comment]
Hi Sven,

There is a problem with the update.
On a third machine Pay make an update. When I connect that machine
Coxswail close immédiatly.
I activate the log but I don't find it. I tried exporting but I don't know
where the file is ?


Visitez www.imagesde.fr

**Comment by JPRAGO** [comment]
Read Play.
When I start rowing S4 start but nothing happen on Coxswain.

Visitez www.imagesde.fr

**Comment by svenmeier** [comment]
Please, create a new issue for other problems -> Green button top left "new issue"!

**Comment by JPRAGO** [comment]
Done.
Visitez www.imagesde.fr
