### ISSUE TITLE
"Challenge" should inherit the workout type

### ISSUE THREAD

**Issue by martinkopcik73** [svenmeier/coxswain#127]
When I challenge the previous workout, the workout is being correctly recorded. The problem is it doesn't show up when listing the workouts of the selected type.
For example I challenged the prevoius 500m workout. After it was finished, it was not listed when 500m workouts were listed. It was listed only in the workouts of that particular day.

**Comment by svenmeier** [comment]
Hi, 
thanks for creating this issue.

The idea was that with "challenge" you want to challenge a previous workout without any program and segment involved.

If you select "Repeat" from the workout menu instead, Coxswain will keep the association with the original program. I think this is what you want to achieve?

**Comment by martinkopcik73** [comment]
You are right, I tried "repeat" and unexpectedly it did exactly what I expected from the chalenge. 
Thank you for pointing it out I'm not using the software right.
I didn't see any difference between those two except that the challenge removed the program association from the result. I don't understand at the moment how it can be useful and why there 2 very similar features.
The name of "repeat" suggested to me I will repeat the same workout program without any comparison. "Challenge" suggested my progress will be compared with the previous workout. But I was going intuitively without reading the manual.
Great app !
