### ISSUE TITLE
USB OTG Android: Sporadic connection losses

### ISSUE THREAD

**Issue by whosnick** [svenmeier/coxswain#128]
I plug in the cable to my phone and then switch on the S4. Coxswain starts automatically. "PC" is always displayed on the S4.

When I start a program, Coxswain will sporadically return to the "choose program" menu, probably because it lost connection? "PC" is always displayed. Selecting a program again will normally again let the S4 "beep" and reset for a new program, without having to reattach the cable.

If this is not a known issue I guess the problem lies with my Android or cable connection?

**Comment by svenmeier** [comment]
If PC ist displayed all the time on the S4, this rather looks like a protocol error.

Please enable "write trace" in Coxswain's settings, then reconnect and row.
When rowing ends prematurely, attach the file "coswain/waterrower.trace" to this issue.

**Comment by whosnick** [comment]
[1620124583660.trace.txt](https://github.com/svenmeier/coxswain/files/6420478/1620124583660.trace.txt)

This should contain two short rows with two "disconnects" back to the program selection screen.

While doing this I noticed that I can force this behavior by taking my phone and letting it rotate the screen from landscape to portrait mode. Every time the screen rotates the program seems to disconnect.

**Comment by svenmeier** [comment]
The log shows a disconnect, probably only a short moment where the connection is lost.

The connection is handled independently from any UI interaction, so screen rotation should have no influence here. Maybe your cable or usb port is faulty.

You could check your phone for a USB power saving mode too.

**Comment by whosnick** [comment]
Thanks for looking into this. Will try another cable once I get one.

**Comment by whosnick** [comment]
New cable solved the issue. Thanks for your support and for this great app!
