### ISSUE TITLE
Allow rowing against previous workouts

### ISSUE THREAD

**Issue by svenmeier** [svenmeier/coxswain#13]
It would be nice to be able to compare the current workout with previous workouts.

Ideas:
- show the estimated total time in comparison to the best total time
- show the estimated total distance in comparison to the best total distance

**Comment by mlaeng** [comment]
Yes. That would be a perfect way to push limits. Also the graphical representation could be adjusted, so you quickly see if you are ahead or behind the previous workouts. It's a bit like that ghost mode in racing games, where you compete against your former self.

**Comment by svenmeier** [comment]
With issue #7 being solved we can now show additional information on the workout screen. 

At the moment I'm thinking about displaying a time delta in relation to the last workout, e.g.
- 15 seconds behind:

    -00:15
     GHOST

- 1 minute ahead:

    +01:00
     GHOST

**Comment by svenmeier** [comment]
The user can choose any of his previous workouts as the pace boat.

**Comment by mlaeng** [comment]
I'll be happy to test this...

BTW: Thanks a lot for all the work lately. I use Coxswain on every training. Export to Google works flawless.  (didn't find time to geive feedback or say thanks yet)

**Comment by svenmeier** [comment]
This will be part of the upcoming version 2.7
