### ISSUE TITLE
Export to Google Fit fails 

### ISSUE THREAD

**Issue by arjunluthra** [svenmeier/coxswain#131]
I have my workouts set to auto export but I didn't see one after my workout today, when I try to manually do it, it shows saying exporting then says export failed.

Happy to get logs but not sure how to.

**Comment by svenmeier** [comment]
So it stopped working from one day to the other?
You can choose "Export application log" in the Coxswain settings. Send me the resulting file, should be "/coxswain/app.log" or similar.

**Comment by arjunluthra** [comment]
Sure thing, emailed.  I see this, not sure how it happened or how to reauth:

05-24 22:27:32.242 17947 17947 E coxswain: googlefit failed
05-24 22:27:32.242 17947 17947 E coxswain: com.google.android.gms.common.api.ApiException: 5000: Application needs OAuth consent from the user

It's been a few weeks since I've done a session, and it worked last time (5/1), I don't recall doing anything to remove access.

**Comment by whosnick** [comment]
I have the same problem. Export worked three days ago:

`
05-25 10:37:40.936 32650 32650 E coxswain: googlefit failed
05-25 10:37:40.936 32650 32650 E coxswain: com.google.android.gms.common.api.ApiException: 5000: Application needs OAuth consent from the user
05-25 10:37:40.936 32650 32650 E coxswain: 	at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(com.google.android.gms:play-services-base@@17.1.0:4)
05-25 10:37:40.936 32650 32650 E coxswain: 	at com.google.android.gms.common.internal.zai.zaf(com.google.android.gms:play-services-base@@17.1.0:2)
05-25 10:37:40.936 32650 32650 E coxswain: 	at com.google.android.gms.common.internal.zak.onComplete(com.google.android.gms:play-services-base@@17.1.0:6)
05-25 10:37:40.936 32650 32650 E coxswain: 	at com.google.android.gms.common.api.internal.BasePendingResult.zaa(com.google.android.gms:play-services-base@@17.1.0:176)
05-25 10:37:40.936 32650 32650 E coxswain: 	at com.google.android.gms.common.api.internal.BasePendingResult.setResult(com.google.android.gms:play-services-base@@17.1.0:135)
05-25 10:37:40.936 32650 32650 E coxswain: 	at com.google.android.gms.internal.fitness.zzaw.setResult(com.google.android.gms:play-services-fitness@@19.0.0:3)
05-25 10:37:40.936 32650 32650 E coxswain: 	at com.google.android.gms.internal.fitness.zzei.onResult(com.google.android.gms:play-services-fitness@@19.0.0:4)
05-25 10:37:40.936 32650 32650 E coxswain: 	at com.google.android.gms.internal.fitness.zzcm.zza(com.google.android.gms:play-services-fitness@@19.0.0:11)
05-25 10:37:40.936 32650 32650 E coxswain: 	at com.google.android.gms.internal.fitness.zza.onTransact(com.google.android.gms:play-services-fitness@@19.0.0:13)
05-25 10:37:40.936 32650 32650 E coxswain: 	at android.os.Binder.execTransact(Binder.java:726)
05-25 10:37:40.959 32650 32650 I Toast   : Show toast from OpPackageName:svenmeier.coxswain, PackageName:svenmeier.coxswain
05-25 10:37:42.364 32650 32673 D OpenGLRenderer: endAllActiveAnimators on 0x72a7f31f00 (MenuPopupWindow$MenuDropDownListView) with handle 0x72a8298720
05-25 10:37:44.940 32650 32673 D OpenGLRenderer: endAllActiveAnimators on 0x72a7f5b600 (AlertController$RecycleListView) with handle 0x72a8220860
05-25 10:37:44.976 32650 32650 I Toast   : Show toast from OpPackageName:svenmeier.coxswain, PackageName:svenmeier.coxswain
05-25 10:37:45.171 32650 32650 E coxswain: googlefit failed
`

**Comment by Aldebaran911** [comment]
Hallo,
ich habe heute ebenfalls das gleiche Problem. Vor ein paar Tagen funktionierte es noch problemlos.

**Comment by paria81** [comment]
Hallo, ich habe ebenfalls das Problem das der Export zu Google Fit Scheiter. Letzter erfolgreicher export war am 17. 05.

Ich habe versucht coxswain in Google fit rauszuschmeißen und neu zu verknüpfen, leider ohne Erfolg.

Auszug aus dem Log:
05-24 23:22:17.893 16398 16398 E coxswain: com.google.android.gms.common.api.ApiException: 5000: Application needs OAuth consent from the user
05-24 23:22:17.893 16398 16398 E coxswain: 	at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(com.google.android.gms:play-services-base@@17.1.0:4)

**Comment by svenmeier** [comment]
Google has restricted access to fit data. I probably missed the announcement or I didn't bother why they make it harder once again to use their services :(.

I will check what has to be changed.

**Comment by dr-loz** [comment]
Thx Seven, Great app! Also worked for me Monday,  since then kaput.

**Comment by svenmeier** [comment]
Strange, exporting to Google Fit works fine for me.

Could you try removing access for Coxswain here https://myaccount.google.com/permissions and then start another export in the App?

**Comment by Aldebaran911** [comment]
Hallo,
das Entfernen der Zugriffsrechte und erneuter Export bringt bei mir nichts.

Sven Meier ***@***.***> schrieb am Mi., 26. Mai 2021, 18:13:

**Comment by svenmeier** [comment]
Which Android version?

**Comment by whosnick** [comment]
I removed the connection via the Google link you provided and then tried another export. It showed failed to export again but then I got the pop-up to rebind the app to my Google account. I did that but the export still fails. I am on Android 9.

**Comment by dr-loz** [comment]
Hey android 10.
I removed account access in Google.
Then tried export... failed ( didn't ask me to link account).
I deleted coxswain cache and data.. restarted.. this time export promoted account link.. export still failed.

**Comment by paria81** [comment]
Same Here, unlink the coxswain App (done this Yesterday more then once) and
Tried to Export again. PopUp -> select Google Account -> export stil fail.

Android 10 MIUI 12

But First time i saw the following Message



dr-loz ***@***.***> schrieb am Mi., 26. Mai 2021, 19:22:

**Comment by arjunluthra** [comment]
Same issue after disconnecting.  Android 11.

Do you need a new log file?

**Comment by svenmeier** [comment]
No, I was able to reproduce the problem on my wife's phone.

**Comment by whosnick** [comment]
I can confirm it works again with app version 8.5. Thanks for your effort, Sven!

**Comment by svenmeier** [comment]
Thanks for reporting back.

**Comment by arjunluthra** [comment]
Confirmed also, thank you very much!
