### ISSUE TITLE
Update 8.6 don't work

### ISSUE THREAD

**Issue by JPRAGO** [svenmeier/coxswain#132]
I update vis Google Play this morning.
The application is in french.
When I connect to the Waterrower , the application immediatly close.
When I open first the application and open a program nothing happen on Phone but S4 start.
That occured on 3 machines.
I active the log but I don't find it.

On 2 machines I desinstall Coxswain and reinstall via Play. It worked.

**Comment by svenmeier** [comment]
Many thanks for reporting this problem.

Please look in the Coxswain settings for "export application log". Activate it and look for the file "/coxswain/app.log" on your device. Send it to me or attach it here by drag&drop.

**Comment by svenmeier** [comment]
Just to make sure this isn't related to the new French translation, you could temporarily switch your system language to French and see whether the problem persists.

**Comment by JPRAGO** [comment]
I try with English and it's the same problem.
I desactivate the function "Calculate speed from power" and close the program. When opening it work.
I see you "adjust distance when adjusting speed"
Could it be a right track ?

**Comment by svenmeier** [comment]
Yes, it seems I've broken something with the speed adjustment. Please attach or send me the log file.

**Comment by JPRAGO** [comment]
I don't have log files. It don't work.

**Comment by svenmeier** [comment]
Do you have a file explore on your phone? Choose "Memory -> Internal memory -> /coxswain/coxswain.log"

**Comment by JPRAGO** [comment]
In coxswain there only 2 files, : gym and gym-journal.
Log is active in preference. Bug ?

**Comment by JPRAGO** [comment]
Trying to create course.tcx or export tcx file failed and nothing in coxwain directoty.

**Comment by svenmeier** [comment]
Then you didn't give Coxswain the permission to access the file system.

As soon as you export something (log or trainings), a popup should ask you whether the App is allowed to do so.

**Comment by JPRAGO** [comment]
The problem is that no popup open.
I try with another machine where I desinstall and reinstall, where tcx work and there is no log..

**Comment by JPRAGO** [comment]
I verify in application and access to multimedia file is autorize

**Comment by JPRAGO** [comment]
Hi Sven,

I deinstall.
I install a 8.4 which work.
I made an update vis Play.
Then problems comes with energie correction active.
I send you attached the file waterrower.trace
Visitez www.imagesde.fr

**Comment by philippn** [comment]
Hello Sven,

please find the attached log file. Thank you so much and keep up the good work!

[coxswain.log](https://github.com/svenmeier/coxswain/files/6572142/coxswain.log)

**Comment by svenmeier** [comment]
Many thanks, that log file is very helpful.

**Comment by svenmeier** [comment]
Fixed with version 8.7

**Comment by JPRAGO** [comment]
First test is OK.
Great thanks Swen.
