### ISSUE TITLE
after upgrade all trainings/programs are lost

### ISSUE THREAD

**Issue by juesteiger** [svenmeier/coxswain#133]
hi sven,

after upgrade to 8.6 all trainings and programms have gone and he says that he could not load the repisitory from external location. after uninstall/install i was asked for permissions to storage, allowed access and it worked. trainings and programms came back. 

now after upgrade to 8.7 same problem. all trainings are away and i can't even export the log file but app has permission to storage? no no way to get them back. 

thxs in advance and br
Juergen

**Comment by svenmeier** [comment]
Argghh, Google disallows access to external storage when targeting API 30 on Android 11.

I will have to address this in a future version, but for now I rolled back to API 29, this should fix the problem if you are using an external storage location for your App trainings. Exports will work again too.

Thanks for reporting, the update is on rollout now.

**Comment by juesteiger** [comment]
thxs so much, works againbrjuergenVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Sven Meier ***@***.***> Datum: 02.06.21  07:41  (GMT+01:00) An: svenmeier/coxswain ***@***.***> Cc: juesteiger ***@***.***>, Author ***@***.***> Betreff: Re: [svenmeier/coxswain] after upgrade all trainings/programs are
  lost (#133) 
Argghh, Google disallows access to external storage when targeting API 30 on Android 11.
I will have to address this in a future version, but for now I rolled back to API 29, this should fix the problem if you are using an external storage location for your App trainings. Exports will work again too.
Thanks for reporting, the update is on rollout now.
