### ISSUE TITLE
Duration of a segment

### ISSUE THREAD

**Issue by Maxdott** [svenmeier/coxswain#134]
Is it possible to extend the duration of a segment to 60 minutes? Thanks Massimo

**Comment by svenmeier** [comment]
Yes, I will make change that for the next released version.

**Comment by Maxdott** [comment]
Thank you! 

⁣Ottieni BlueMail per Android ​

Il giorno 15 lug 2021, 09:03, alle ore 09:03, Sven Meier ***@***.***> ha scritto:
