### ISSUE TITLE
Import TCX files

### ISSUE THREAD

**Issue by Polimagoo** [svenmeier/coxswain#136]
Hi, I have tried importing TCX files created with a notepad on windows 10 and copied on a SamsungS10 Android 11 with no success.
I get a " file import failed" message.
So I have exported (with no problem) a sample workout file already created in Coxswain (the 10 minutes workout). I used wordpad to change the name and add .tcx extension to be able to import it.
File name is "testminutes.tcx"
Here is the content of the file :
{
"name": "testminutes",
"segments": [
{
"difficulty": "MEDIUM",
"duration": 600
}
]
}

But thid doesn't work either. I get the "import failed" message
Is there something missing ?
Thanks.
Best.

**Comment by svenmeier** [comment]
Wordpad is probably insert some illegal hidden characters.

You could try with a 'real' editor like notepad++ (https://notepad-plus-plus.org/).

Or use "export application log" in Coxswain's setting and a send me exported file /coxswain/application.log so we can check the actual problem.

**Comment by Polimagoo** [comment]
Hi Sven, thanks for your anwser. 'Real" editor didn't seem to be successfull either. Here is the log file
Thanks a lot for great work.
Kind regards.
Laurent
[coxswain.log](https://github.com/svenmeier/coxswain/files/7758198/coxswain.log)
.

**Comment by svenmeier** [comment]
```
Unexpected token (position:TEXT ��{\C0\80
12-21 21:00:41.930 26053  6094 E coxswain: \C0\80 \C0\80 \C0\80"\C0\80n\C0\80a\C0\80
```
Could you please attach your edited file please?

**Comment by Polimagoo** [comment]
Here it is. (To be able to upload it here, I changed the extension of the file from tcx to txt
 Thanks
[testminutes.txt](https://github.com/svenmeier/coxswain/files/7761820/testminutes.txt)
.

**Comment by svenmeier** [comment]
With the .tcx extension Coxswain thinks you want to import a training in tcx XML format.

The file has to have the .coxswain extension to be identified as a trainig program.

    I used wordpad to change the name and add .tcx extension to be able to import it.

Why did you have to rename it?

**Comment by Polimagoo** [comment]
Hi Sven,
My understanding of TCX file was based on the explanation "This is how a TCX file looks like" in the wiki.
Now I did it all over again, exporting the .coxswain file, edit it with the "real" notepad++ and import it back, not changing the extension.
That works fine.
Thanks.
Best.

**Comment by svenmeier** [comment]
Ah, that was a bit misleading indeed.
