### ISSUE TITLE
Abweichung zwischen coxswain und S4; Versionsanzeige; Installation aktuelle Version unter Android 5

### ISSUE THREAD

**Issue by schusssel** [svenmeier/coxswain#139]
Hallo,

erstmal möchte ich mich für die grossartige Software bedanken, die mich schon durch viele Training begleitet hat.
Vielen Dank für die viele Arbeit und Mühe, die darin eingeflossen ist.

ich habe zwischen coxswain und dem S4 Monitor eine Abweichung von ca 10%. So steht der S4 Monitor nach Beendigung des 5000m Programms (vom coxswain) bei ca. 5500m. Ist das bekannt bzw. kann ich das irgendwie beheben?

Verbindung zwischen coxswain (Tablet) und dem S4 Monitor erfolgt per USB Kabel.

Gibt es in coxswain eine Versionsanzeige der installierten Version, bzw. wie lässt sich das herausfinden? (im Log oder ähnliches?)

coxswain läuft hier auf einem alten FireHD 8 (7. Generation) Tablet von amazon, dass auch nur noch für den Waterrower genutzt wird. Seit einiger Zeit kann ich aber die apk aus dem Github nicht mehr installieren. Gab es irgendwann mal einen Breake, der eine bestimmte Android Version vorraussetzt? Auf dem FireHD Tablet läuft FireOS 5.3.7.0. Installierte coxswain Version kann ich leider nicht sagen, siehe Frage nach der Versionsanzeige.

Mit freundlichen Grüssen

Thomas

**Comment by schusssel** [comment]
Hier das Logfile nach einem 1000m Programm + Bild um die Differenz zu zeigen.

[coxswain.log](https://github.com/svenmeier/coxswain/files/8952839/coxswain.log)
![rower](https://user-images.githubusercontent.com/21107036/174899199-7158ed65-3175-46f2-acea-06d0241c29c9.jpg)



(Über den google PlayStore habe ich mittlerweile auch die V8.8 installiert bekommen. Obwohl mir der Weg über die Github apk lieber waere. Aber da krieg ich immer eine Fehlermeldung, dass das parsen des Pakets nicht erfolgreich war)

**Comment by svenmeier** [comment]
Bitte schalte mal in den Einstellungen "Ruder-Protokoll mitschreiben" ein.

Dann schreibt Coxswain beim nächsten Rudern eine Protokolldatei in /coxswain/waterrower.trace - bitte diese Datei dann auh noch anhängen. Danke.

**Comment by schusssel** [comment]
> Bitte schalte mal in den Einstellungen "Ruder-Protokoll mitschreiben" ein.
> 
> Dann schreibt Coxswain beim nächsten Rudern eine Protokolldatei in /coxswain/waterrower.trace - bitte diese Datei dann auh noch anhängen. Danke.

Hier vom gestrigen Training.
(Hab die .trace und . tcx nach .txt umbenannt, damit ich sie hier hochladen kann)

Wenn ich noch irgendwas tun kann, gerne melden.


[coxswain.log](https://github.com/svenmeier/coxswain/files/8985509/coxswain.log)

[waterrower_trace.txt](https://github.com/svenmeier/coxswain/files/8985514/waterrower_trace.txt)

[2022-06-24_20-51-13_600 Züge_tcx.txt](https://github.com/svenmeier/coxswain/files/8985515/2022-06-24_20-51-13_600.Zuge_tcx.txt)

**Comment by svenmeier** [comment]
Vielen Dank, aber leider pass die trace-Datei nicht, sie ist zu kurz.
Wahrscheinlich hat du ein erneutes Training kurz gestartet, dann wird der Inhalt wieder überschrieben.

Kannst du bitte die Kombination trace und tcx noch einmal erzeugen? Danke.

**Comment by schusssel** [comment]
> Vielen Dank, aber leider pass die trace-Datei nicht, sie ist zu kurz. Wahrscheinlich hat du ein erneutes Training kurz gestartet, dann wird der Inhalt wieder überschrieben.
> 
> Kannst du bitte die Kombination trace und tcx noch einmal erzeugen? Danke.

Sorry, dass ich mich jetzt erst melde, war beruflich sehr eingespannt.

Mittlerweile hat sich die Ausgangsituation verändert. Mein amazon Tablet hat sich leider in einem fremden WLAN Updates gezogen (zuhause wird das über die Kindersicherung der FritzBox untersagt). Eigene Dummheit.
Danach wurde weder mein Brustgurt (Polar H10) per Bluetooth ordentlich empfangen noch wurde dieser in Coxswain erkannt. Beides hat vorher problemlos funktioniert. Zu allem Ärger hat das FireOS Update auch noch alle meine Trainings zerlegt.

Naja. Return to Zero :-)

Damit ich endlich von dem amazon Crap auf dem Tablet loskomme habe ich die Chance genutzt  und das Tablet mit LineageOS versehen. Nun werkelt dort ein LineAgeOS 15.1 auf Android Basis 8.1.0. Leider lässt sich aber auch hier nicht mehr die github apk (8.8) von coxswain installieren. Die Fehlermeldung vom Tablet "App wurde nicht installiert" ist leider nicht sehr aussagekräftig.

per adb probiert, kommt folgende Fehlermeldung (vielleicht aussagekräftiger):
`adb install app-release.apk
Performing Streamed Install
adb: failed to install app-release.apk: Failure [INSTALL_FAILED_TEST_ONLY: installPackageLI]`

Eine Idee, ob in den letzten apk Versionen von coxswain eine Abhängigkeit zu höheren Androidversionen (> Android 8) hinzugekommen ist?
Mit anderen runtergeladenen apk Dateien bei der Tablet Neuinstallation hatte ich bisher keine Probleme.


Um das alte Problem (Differenzen in der Ruderdistanz zwischen S4 und Coxswain) zu beheben, müsste ich also erstmal das neue Installationsproblem lösen. Dann kann ich auch die angefragten trace Dateien posten.

Eine Installation aus dem Google Play Store will ich mir ersparen!

**Comment by svenmeier** [comment]
Hm, ich selber habe das APK von Github noch nie installiert.
Probierst du das hier mal aus:
https://lynxbee.com/resolved-failure-install-failed-test-only-installpackageli/
