### ISSUE TITLE
How to end training?

### ISSUE THREAD

**Issue by kgroshert** [svenmeier/coxswain#141]
I feel a bit stupid for even asking, but how do I end training?

I have connected the Waterrower to PiRowFlo which sends data to Coxswain by bluetooth.
Everything seems to work fine, data is displayed in Coxswain while rowing.

But how to end & save training? If I press the back button in Android I get back to the "Programm" screen and the running
program ist displayed on top but I can only press the "x" which will close it without saving. But how to save? Am I missing something obvious?

**Comment by svenmeier** [comment]
The training ends when the target the program (distance, time, strokes or energy) is reached (this can be disabled in the settings), the rower is disconnected or you end the training by the "x" on top of the main screen.

Regardless how, a running training is saved every second automatically. When you swipe to the right on the main screen, you should see the recorded trainings.

**Comment by kgroshert** [comment]
Works like a charm now after I reinstalled Coxswain. I had it installed (but not used) for a long time - I suspect maybe Android took some of the permissions away.
All good now, thx!
