### ISSUE TITLE
Feature request: Turn off sounds

### ISSUE THREAD

**Issue by mlaeng** [svenmeier/coxswain#15]
I am often rowing with earbuds watching Netflix or so. I always need to turn down that whistle sounds because I don't really need them in my current rowing routines. It would be great to have an option to keep it silent at all.

**Comment by svenmeier** [comment]
You can configure the sounds in the App settings, just set them to "none".

**Comment by svenmeier** [comment]
Coxswain 3.9 will add a preference check to enable/disabled all sounds.
