### ISSUE TITLE
Feature request: Connect to Google Fit

### ISSUE THREAD

**Issue by mlaeng** [svenmeier/coxswain#17]
I use Google Fit to keep my data together. It would be great if Coxswain had the option to connect / record the data in Google Fit.

here's some info about that: 
https://developers.google.com/fit/

and about the recordings:
https://developers.google.com/fit/android/record

The cool thing is that Google Fit connects to tons of other apps. So the data I recorded on Google FIT is available in various other apps like Withings or MyFitnessPal etc.

**Comment by svenmeier** [comment]
Interesting proposal, thanks!

It seems we could bulk import workouts via the history API:

    https://developers.google.com/fit/android/history

**Comment by svenmeier** [comment]
An experimental implementation will be part of version 2.3.

**Comment by ahvanderboon** [comment]
Hi, just tried the export to Google fit. Unfortunately the distance did not come through and the calories burnt do not match those recored in Coxswain itself. Is this a known issue in the experimental implementation?

**Comment by svenmeier** [comment]
Calories are not exported currently, so I suspect Google Fit is using a different algorithm. I will change Coxswain to export TYPE_CALORIES_EXPENDED too.

**Comment by svenmeier** [comment]
I'll check the missing distance, see #30.
