### ISSUE TITLE
Feature request: Calculate stroke ratio (is that possible at all)

### ISSUE THREAD

**Issue by mlaeng** [svenmeier/coxswain#18]
The S4 menu option, where it can show you the stroke ratio. It then displays it every 10 seconds or so. But it's displayed for a very short time. It would be great if Coxswain was able to display the actual stroke rate, but I am note sure if you could get that from the readouts...

**Comment by svenmeier** [comment]
From the USB protocol:

stroke_average 142 ; average time for a whole stroke
stroke_pull 143 ; average time for a pull (acc to dec)

"Stroke_pull is first subtracted from stroke_average then a modifier of 1.25 multiplied by the result to
generate the ratio value for display."

So yes, it seems we can get the stroke ratio from the S4.

**Comment by svenmeier** [comment]
Calculating and storing the stroke ratio is easy. We have to find a solution for #20 to display it.

**Comment by svenmeier** [comment]
This feature will be available in the upcoming version 2.4
