### ISSUE TITLE
Feature proposal: Total data

### ISSUE THREAD

**Issue by mlaeng** [svenmeier/coxswain#19]
I am sorry, I don't want to spam your issue tracker with ideas/feature requests (will call them proposals from now on), but I have another one: it would be cool to have a total of all the trainings I did, so I could see how many KM, kcals, hours or strokes I already killed on my rower.

It would also be another incentive to use coxswain for every single training.

It would basically be just the sum of the data in the 'trainings' table.

**Comment by svenmeier** [comment]
On the performance tab, you can zoom out until you see the totals for each month. Is this what you are looking for?

**Comment by svenmeier** [comment]
Just use the performance tab.
