### ISSUE TITLE
tcx upload to runtastic fails

### ISSUE THREAD

**Issue by Jo11n** [svenmeier/coxswain#21]
Trying to upload a coxswain file in Runtastic fails. This is the error message of the website:

>Why an error occurred?
>
>There are various possibilities why your data import could not be completed:
>    Your file is missing location or time data and no sport activity can be generated from it.
>   The data of your file is malformed and does not match the specification for the filetype.
>   The uploaded file is not a valid TCX or GPX file.

**Comment by svenmeier** [comment]
Could you please attach your TCX file to this issue? You can just drag it into a new comment.

**Comment by svenmeier** [comment]
Never mind, I've tried with one of my workouts and it failed too.

**Comment by svenmeier** [comment]
I found the reason:

Runtastic actually expects a position element in the file:

    <Track>
      <Trackpoint>
        <Time>2016-06-05T12:35:13Z</Time>
        <Position>
          
        </Position>
      ...
    ...

**Comment by svenmeier** [comment]
Coxswain 2.5 will store the location of a workout and will export it as the <Position> of the first trackpoint.
