### ISSUE TITLE
Replace colons in tcx-filenames

### ISSUE THREAD

**Issue by Jo11n** [svenmeier/coxswain#25]
I was puzzled because Dropbox would not sync the tcx files generated by coxswain. Turns out, unfortunately (and inexplicably) colons are still illegal characters in file names in Windows. Would you mind replacing them with something else? Underscores would work for me. If you want, you can also use a unicode alternative, such as U+A789 or U+FF1A. Thanks!

While you're at it: May I suggest to put date and time in front and the workout name in the end of the filename? This would make it easier to keep track of the workouts, imho. Thanks!

**Comment by svenmeier** [comment]
Starting with the next version the filename will be yyyy-MM-dd_HH-mm-ss_workout.tcx.
