### ISSUE TITLE
Feature request: Microsoft Band 

### ISSUE THREAD

**Issue by ahvanderboon** [svenmeier/coxswain#28]
Is there a way for you to pick up the hart rate feed (and other physiological measures) from Microsoft Band?

**Comment by svenmeier** [comment]
It seems the Microsoft Health App has to be installed.
But sensor data isn't available via Android's standard API:
    http://developer.microsoftband.com/Content/docs/Microsoft%20Band%20SDK.pdf

This would require us to add custom functionality to Coxswain - while possible, it is very unlikely I'll have time to work on that :(.

**Comment by ahvanderboon** [comment]
Thank you. Understand.

**Comment by svenmeier** [comment]
Even worse, Microsoft dropped support for its Band SDK.

**Comment by ahvanderboon** [comment]
Thanks for following up Sven.


Sent from my Samsung Galaxy smartphone.


-------- Original message --------
