### ISSUE TITLE
Feature Request: Sharing Programs and Workouts

### ISSUE THREAD

**Issue by Crispylettuce** [svenmeier/coxswain#35]
It would be good to be able to share programs and workouts with fellow Coxswain app users.

Sharing programs - enables you to share set workout programs with other people

Workouts - enables you to use another users past workout as a pace-boat

On the whole its a great app, simple to use and intuitive. Thanks.

**Comment by svenmeier** [comment]
The upcoming version will support sharing of workouts.

**Comment by Crispylettuce** [comment]
Howdy. Whilst I can see an export feature, how does someone else import this workout on that phone?

**Comment by svenmeier** [comment]
I'll check again.

**Comment by svenmeier** [comment]
Seems Coxswain has to check for additional intent properties, to support importing from different programs.

With the next version this is tested to work with BlueMail, Google Drive and File Manager.

**Comment by svenmeier** [comment]
Just added another improvement: imported workouts are now linked with an existing program with identical name.
This will be available with Coxswain 3.6.
