### ISSUE TITLE
Feature Request: Ability to pause

### ISSUE THREAD

**Issue by IwishIcanFLighT** [svenmeier/coxswain#36]
Hi,
It would be great to be able to pause a run via a button on the app.
It's already possible to pause on the s4 monitor, but the app is not notified and keeps ticking. Maybe we can link them together. 

Amazing job on this app btw, I use it every single day. Keep up the good work!

**Comment by svenmeier** [comment]
I'll have to investigate how pause can be supported.

The S4 sends Code "AK9" when the "Hold" button is pressed, so pausing from here should work.

**Comment by IwishIcanFLighT** [comment]
Thanks!

**Comment by svenmeier** [comment]
Interactive mode is no viable solution:
- it has to be activated explicitly on the S4 by the user (I'm not sure how it is done actually)
- while in interactive mode the "Hold" button is transferred, but S4 itself does not stop the timer.

It's probably easier to let Coxswain use the S4's timer instead - currently Coxswain has its own timer. So pressing "Hold" will stop the timer on the S4 and in Coxswain too.

**Comment by svenmeier** [comment]
On upcoming Coxswain 3.6 a workout can be paused with the "Hold" button on the S4.
