### ISSUE TITLE
Feature: S Health integration

### ISSUE THREAD

**Issue by andreasvc** [svenmeier/coxswain#39]
Would be great if Coxswain could automatically log duration and calories burned in S Health.

Great app BTW!

**Comment by svenmeier** [comment]
Well another export would be needed, inserting acquired data into S Health:

    http://img-developer.samsung.com/onlinedocs/health/com/samsung/android/sdk/healthdata/HealthDataResolver.InsertRequest.html

Then we might add an option to make any of the available exports automatic.

**Comment by svenmeier** [comment]
Exports are automatic now, support for S Health will be delayed until we have more interest in this.
