### ISSUE TITLE
Feature suggestion: Save kcal data in training summary

### ISSUE THREAD

**Issue by Jo11n** [svenmeier/coxswain#4]
I realize that the kcal-estimate of the waterrower must be pretty crude. Nevertheless it would be great if this data could be saved in the workout summary. At the moment, it can't be accessed anymore after the coxswain workout has ended because the S4 just switches off. Thanks!

**Comment by svenmeier** [comment]
I can configure my S4 to show the intensity in cal/hr (instead of m/s), but this is a temporary reading only. Does it even make sense to store this value? Or do you mean something different? If so, could you please describe how you configure your S4 for that?

**Comment by Jo11n** [comment]
My S4 has a "kcal" output in the "distance" portion of the display (lower right quadrant) showing the total calorie expenditure for the workout. I can set it by cycling through the display settings with the "unit" and the arrow buttons.
 
Apparently, in older monitors, the kcal output is a hidden feature: 
http://www.waterrowerservice.com/settings-calories-burned/

**Comment by svenmeier** [comment]
Oh, I see. I have the kcal unit available too, I just didn't know it was there :).

Instead of taking the value from the WaterRower, I'd rather calculate it in Coxswain (and the display it in the workout history). Your body weight could be another setting in the app.

Any idea on how to calculate this? Something like:

    calories = average speed * duration * (weight * X) * Y

**Comment by Jo11n** [comment]
Another variable is the amount of water in the tank. My understanding is that the S4 has an algorithm to estimate the amount of objective mechanical work subjected to the Waterrower. The water level (which can be set in the S4) seems to be one variable that goes into that computation. See [here] (http://www.waterrower.biz/graphics/pdf/s4_processing_algorithm.pdf) for some info on the physics and the math. I guess, the amount of work is then converted into a rough estimate of calorie expenditure based on some assumptions.

For the Concept2, the mechanics and the formula are explained [here] (http://eodg.atm.ox.ac.uk/user/dudhia/rowing/physics/ergometer.html#section11). A typical assumption seems to be an efficiency factor of 25% and an added constant of 300 kcals/hour of "background consumption".

In addition, there is an assumption about the body weight of the rower. According to a comment on this facebook [post] (https://www.facebook.com/WaterRower/posts/930624596988532:0) by WaterRower, the S4 calculation assumes a body weight of 150 pounds.

Thus, the best estimate would probably be to convert the estimate of mechanical work during the workout to kcals with the actual body weight, or adjust the calorie estimate for body weight (as can be done [here] (http://www.concept2.com/indoor-rowers/training/calculators/calorie-calculator) for the Concept 2). However, for this one would need more info about the WaterRower algorithm.

I for one would be happy with the estimate of the S4 as one that should be somewhere in the right ballpark (I happen to weigh around 150 pounds, I must admit though).

**Comment by svenmeier** [comment]
Ok, I'll think for now we'll just take the value from the waterrower. I'll try it out and report back.

**Comment by svenmeier** [comment]
Version 1.4 records kcal and displays the value for each workout in the list.

Improving the kcal calculation and display will be handled in other issues.
