### ISSUE TITLE
HR BLE not working

### ISSUE THREAD

**Issue by Zabolicoce** [svenmeier/coxswain#40]
I have tried to use a HR BLE, unfortunately with no success.
HR BLE: SP-HRM-BLE-200
Coxswain 3.6 
Sony Z5 Compact Android 6.0.1
Sensoren: Puls lesen von Bluetooth 
Theo same HR BLE works without problems on the same device with other apps (e.g. oruxmaps).

**Comment by svenmeier** [comment]
Could you please report which messages are displayed by Coxswain when you connect your Waterrower?
("Kein Bluetooth verfügbar", "Kein Bluetooth LE verfügbar", "Standortdienste müssen zum Zugriff auf Bluetooth aktiviert sein", "Kein Puls über Bluetooth gefunden").

Thanks.

**Comment by Zabolicoce** [comment]
Hi,

There is no message, everything works only heart rate is not displayed.
Due to your hint regarding the expected messages I have checked the app permission settings.
All the requested permissions where deactivated. When I activate all app permissions including global google locations everything works :-)
Now I am not shure if I have deselected the permissions after installation or if this is the default setting after installation.
To save battery I have normally deactivated the global locations setting. 
If the app permissions are allowed and the global locations settings are deactivated and I connect the device to the waterrower and start the app a message pops up that locations is needed.
Why is locations for access to bluethooth necessary? In oruxmaps bluethooth heart rate works without locations and that is a tracking/navi app which is sensless without locations.

Other point:
It seems that heart reate works only if the app is connected to the waterrower.
My expectation was that heart rate works if a program is selected and bluethooth or ANT+ or Sensor is selected.
That means that heart rate works as soon as a heart rate sensor is available. 

Very nice and clear app!

**Comment by svenmeier** [comment]
>All the requested permissions where deactivated

Coxswain requests all required permissions as it needs them, so normally you should see the usual Android 6 permission requests. I have no idea why this didn't work out on your phone :/.

> if I have deselected the permissions after installation or if this is the default setting after installation.

All permissions are deactivated when you install the App and then activated whenever the App requests them and the user grants them.

>To save battery I have normally deactivated the global locations setting.

Me too :)

> Why is locations for access to bluethooth necessary?

This is a new rule since Android 6, that location service have to be enabled to connect to bluetooth le devices:
    http://stackoverflow.com/questions/33043582/bluetooth-low-energy-startscan-on-android-6-0-does-not-find-devices/33045489#33045489

> In oruxmaps bluethooth heart rate works without locations

That is strange, I wonder how they do it.

>It seems that heart reate works only if the app is connected to the waterrower.

Yeah, that was the intention: connect the Waterrower and *then* the App connects to your heart sensor automatically. I'm sorry that this wasn't clear.

Many thanks for your feedback.

**Comment by svenmeier** [comment]
I've just tried out oruxmaps and you're right, it connects without location services.

I'll investigate this.

**Comment by svenmeier** [comment]
As a follow up:

Apps can be built against an API<23 (Android.M), effectively lifting the requirement to enable location services.

This cannot be done easily with Coxswain though.
