### ISSUE TITLE
Show precise duration in list of workouts

### ISSUE THREAD

**Issue by andreasvc** [svenmeier/coxswain#41]
Currently, my times on 2km and 500m are shown rounded down to minutes in the list of workouts, which is of course not informative. When I open the graph I can zoom in and get a better approximation, but it would be best to just show seconds and fractions of seconds in the list of workouts, e.g., "6:49.5".

To save space, you could leave out "minutes" and abbreviate "meters" to "m", by the way.

**Comment by svenmeier** [comment]
Coxswain doesn't read second fractions currently (neither does it store it) :(.

But I agree that showing seconds in the workout list would be an improvement.

**Comment by svenmeier** [comment]
Upcoming version 3.7 will display a workout's duration in format h:mm:ss.
