### ISSUE TITLE
Export

### ISSUE THREAD

**Issue by gogolo2** [svenmeier/coxswain#42]
Issue: Export to tcx isn't working ("gescheitert") be it locally or by share. I'm on CM14 on a S3. 

Feature request: Export all at once or auto export locally & cloud. 

Coxswain is great, thx very much!

**Comment by gogolo2** [comment]
Addition: I have no gapps installed.

**Comment by svenmeier** [comment]
Installation of gapps should not make any difference.

TCX export works fine here, so I suspect something special on your device:
- please check the app permissions, whether Coxswain has been granted write access (it has been reported by another user that the permission requests didn't show up)
. what is the name of your workout's program? Any special characters contained?

Thanks
Sven

**Comment by gogolo2** [comment]
Thx, storage permission was granted but I had to turn it off and on again manually to get it working. Now everything is fine.
Greetings Olivier

**Comment by svenmeier** [comment]
Ok, please open a separate issue for the feature request.

Thanks.
