### ISSUE TITLE
Feature suggestion: Short durations, rest intervals & heart rate indicator

### ISSUE THREAD

**Issue by stefdrax** [svenmeier/coxswain#44]
Hi,

I really like the app and am so grateful to be able to use it with my Waterrower, thank you very much for developing it!

As I sometimes use very short workout intervals (for max power bursts) I was wondering would it be possible to be able to enter the duration manually via number pad or at least have an 0.5' and 1.5' interval added to the available selection?

Best Regards

Stefan

**Comment by svenmeier** [comment]
Thanks Stefan for your feedback.

I've moved "Rest periods" and "Heart rate indicator" to issues #45 and #46 respectively.

Regarding short segment durations: I've followed your suggestion and added 0:30 and 1:30 minutes to the available value. This will be available in Coxswain 3.9

Have fun

**Comment by stefdrax** [comment]
Thank you so much, I really appreciate your help! Keep the good work up :-)
