### ISSUE TITLE
Improvement: Split window support

### ISSUE THREAD

**Issue by marcoemanuelecocco** [svenmeier/coxswain#48]
It would be useful to implement the following functions: 
rhythm of rowing marked by a metronome, so you can keep the number of rowed per minute set
 it would also be useful to be able to use the program in double window so you can put the music or YouTube video in the background

**Comment by svenmeier** [comment]
Many thanks for your suggestions.

I've added the metronome idea to #32 (traning focus).

Regarding split window? On Android 7 you can already put Coxswain into a split window mode. Do you have any special support in mind that can improve this?

**Comment by marcoemanuelecocco** [comment]
In Android 6 is impossible.
I wait the update for my Huawei m3

**Comment by svenmeier** [comment]
Split window is supported by newer Android versions.
