### ISSUE TITLE
Don't display pulse during workout or in graph when not recorded / 0

### ISSUE THREAD

**Issue by andreasvc** [svenmeier/coxswain#50]
When not displayed during workout, could be replaced by energy (kcal).

**Comment by svenmeier** [comment]
Closing as duplicate of #53

**Comment by andreasvc** [comment]
It's not a duplicate of #53, I'm suggesting the absence of the heart rate monitor should trigger not displaying pulse information.

**Comment by svenmeier** [comment]
The user can choose what values to display via long-press. I won't add an automatic replacement.
