### ISSUE TITLE
Proper x/y axis ticks

### ISSUE THREAD

**Issue by andreasvc** [svenmeier/coxswain#51]
It is currently difficult to read the graphs, since both the x and y ticks are displayed horizontally on the x-axis. Most relevant would be to be able to quickly see the y-values of the average and any peaks.

**Comment by andreasvc** [comment]
A related issue I noticed is that when I have rowed e.g. 90 minutes, the line in the workout graph doesn't reach the tick at 1:30, but seems to stop at about 1:28.

**Comment by svenmeier** [comment]
Could you export your workout and attach it here please?

**Comment by andreasvc** [comment]
[rowing.zip](https://github.com/svenmeier/coxswain/files/1294143/rowing.zip)
![screenshot_2017-09-11-23-26-36](https://user-images.githubusercontent.com/261460/30298052-453d369a-974a-11e7-8f0b-903917c817be.png)

**Comment by andreasvc** [comment]
In the above screenshot the error is only a few seconds, but when I zoom out the error is about 2 minutes.

**Comment by svenmeier** [comment]
Graphs got a mayor overhaul.
