### ISSUE TITLE
Feature: configure information displayed during workout

### ISSUE THREAD

**Issue by andreasvc** [svenmeier/coxswain#53]
motivation:
- currently, 6 variables are displayed during a workout; focusing on just 2-4 might be less distracting during rowing
- when rowing for a calorie target, calories are not displayed

**Comment by svenmeier** [comment]
While in the workout activity, you can press once to leave immersive mode, then press long on a displayed value to change what is displayed there.

We might make the count of displayed values configurable though.

**Comment by svenmeier** [comment]
Next version will allow to change the count of variables to be displayed.
