### ISSUE TITLE
Importing .tcx to Runkeeper fails with Invalid file error message

### ISSUE THREAD

**Issue by brucejackson** [svenmeier/coxswain#57]
It seems that Runkeeper requires a Position for each Trackpoint otherwise the import will fail with an error message stating the file is invalid.

To test, I edited a existing tcx file and added a position for each trackpoint.  I could then successfully import the file to runkeeper. 

Code I added:
`<Position>
<LatitudeDegrees>45.3</LatitudeDegrees>
<LongitudeDegrees>-75.7</LongitudeDegrees>
</Position>`

This runkeeper support article states: "only GPX/TCX files with GPS data can be imported to our website at this time."   (https://support.runkeeper.com/hc/en-us/articles/201109816-How-To-Import-GPX-TCX-Files-On-The-Runkeeper-Website) 

Thanks for this app.

**Comment by svenmeier** [comment]
Many thanks for your detailed analysis.

**Comment by svenmeier** [comment]
Coxswain is writing a position into the first trackpoint only, this way **runtastic** accepts the txc.
I'll change it to write the position into each trackpoint.

Does **runkeeper** accept the txc file if all positions are 0?
This is the current default if Coxswain can't determine the position of the device.

**Comment by svenmeier** [comment]
Great!

1 would definitely be preferred, but 2 would be doable too.

**Comment by brucejackson** [comment]
I agree that 1 is preferred. I have already received a note from RunKeeper saying that they will look at my request but no promises they prefer to make changes that will "bring value to tons of members"...

I've done some digging and found the formulas and a java library for you that can do the calculations.  

A basic description of the formula is on this page, http://www.movable-type.co.uk/scripts/latlong.html, scroll down to the heading "Destination point given distance and bearing from start point".  

This library (https://github.com/JavadocMD/simplelatlng/) includes a function to perform the above calculation.  See: 
https://github.com/JavadocMD/simplelatlng/blob/master/src/main/java/com/javadocmd/simplelatlng/LatLngTool.java#L155

I think this can give you something to think about if you have the time.  

Thanks,
Bruce.

**Comment by svenmeier** [comment]
Coxswain 4.4 will write a track into the TCX: starting with the workout location (Greenwich if not known) and going towards the equator. Let's see whether this works with Runkeeper.

**Comment by svenmeier** [comment]
I've uploaded a workout, perhaps you give it a try with Runkeeper?

[2017-05-11_10-22-39_Segmente.tcx.txt](https://github.com/svenmeier/coxswain/files/992406/2017-05-11_10-22-39_Segmente.tcx.txt)

**Comment by brucejackson** [comment]
That's great.  It uploads fine. Here is the workout as runkeeper sees it.  Thank for adding this capability.

![image](https://cloud.githubusercontent.com/assets/1219029/25947636/4e1e9c6e-361e-11e7-8489-870ec909b0e2.png)
