### ISSUE TITLE
Option to use Concept 2 Math

### ISSUE THREAD

**Issue by johnteh00** [svenmeier/coxswain#59]
dear sven, let me first thank you for this great pice of software!! Made my rowing routine more fun.

I stumbled upon this article (http://www.olympum.com/sports/rowing-with-waterrower-in-zwift) where in the beginning the author talks about the inaccuracy of the waterrower’s pace readings vs. its rather accurate power measurement. 
It could be great to have an option in the settings to switch to c2 math, therefore ignoring the pace related readouts from the S4 and recalculate them via this formula: pace = ³√(2.80/watts) (http://www.concept2.com/indoor-rowers/training/calculators/watts-calculator)

**Comment by svenmeier** [comment]
Good point, I'll see whether we can get our own calculation into the next Coxswain version.

**Comment by svenmeier** [comment]
Implemented for 4.5
