### ISSUE TITLE
TICKR X 

### ISSUE THREAD

**Issue by fredrikbodelson** [svenmeier/coxswain#66]
Hi, first off all thank you for this great application!

I'm trying to get a TICKR X to work with the app but I have only succeeded once after a lot of testing different approaches. I can't figure out exactly what made it work that one time. Is there a specific way to make it work?

I run Android 7.1.1 (unrooted Sony Xperia Z5).

Cheers,
Fredrik

**Comment by svenmeier** [comment]
I'm assuming  you're using a Bluetooth connection and you've configured Coxswain to use a Bluetooth heart sensor?

How well does your phone connect to the tickr with other

**Comment by fredrikbodelson** [comment]
Thank you for your reply, yes you are correct in that I have enabled the Bluetooth setting in Coxswain.

The TICKR X connects to various other fitness apps without any major problems, Strava, Wahoo Fitness, Wahoo Utility, Sportstracker PRO are the ones I'm using in my phone at the moment and they all can connect o the TICKR X. The only issue that I have had before with another app is Sportstracker PRO, to get the connection up and running I sometimes have to start Wahoo Fitness and when that app have recognized the TICKR X, Sportstracker PRO also sees the device.

These are some of the scenarios I have tested (feels like I have tried every possible combination of actions):

I always begin with connecting the USB OTG cable to the S4. Then I must choose "Identify USB device" on my phone. The S4 is then detected and Coxswain is automatically started and a small notification appears with a text similar to "Searching for Bluetooth..." (can't remember the exact reading).

I wait for some minute and then a new notification shows with a text similar to "No Bluetooth was found..".

I have also tried to go into Bluetooth settings directly after Coxswain start to search för Bluetooth and there selected to start a Bluetooth scan. The TICKR X is then sometimes shown in found devices but no success in Coxswain. I have also tried to add the TICKR X to paired devices before the whole process of connecting to the S4.

I have then also tried to start Wahoo Fitnes/Strava/Wahoo Utility/Sportstracker PRO after Coxswain start to search för Bluetooth and in these apps the TICKR X is shown and I can see a heartbeat being reported.

Once I have gotten the Coxswain to connect to the TICKR X and I could see the heartbeat in Coxswain. I think this was after doing a scan for Bluetooth devices in the Bluetooth settings in the phone and also starting Google Fitness during the time that Coxswain is searching for Bluetooth but I have been able to get it to work in that way ever since.

I have also opened the settings for permission for Coxswain and made sure it had all shown permissions enabled. I have also Location/GPS enabled with the highest accuracy setting enabled. I also have enabled the setting under Location for always enabling Bluetooth to discover Bluetooth devices.

Do you know of any debug logs from the Coxswain app or from Bluetooth connectivity that I can dig into or post here?

Cheers,
Fredrik

**Comment by fredrikbodelson** [comment]
Apparently the Xperia Z5 supports ANT+ (and so does the TICKR X), I'll give that a try tonight.

/F

**Comment by svenmeier** [comment]
Glad you've got a workaround.

If you have some time you could follow these instructions https://spryfox.zendesk.com/hc/en-us/articles/218506108 **after** a failed bluetooth connection attempt, to send me debug informations.

There's something sketchy about Coxswain's bluetooth implementation and I'd would really like to fix this.

**Comment by MVermeij** [comment]
Last week I bought a waterrower and just discovered this very useful app. Yesterday I purchased a Wahoo TICKR in order to use it with this application. However it does not seem to connect. I can use it with various other apps. I have created a debug log. If this helps, I can send it to you, if you indicate how and where to send it. 

Kind regards,

Maarten Vermeij

**Comment by svenmeier** [comment]
Please check the app permissions first, Coxswain should be allowed to access location data.

But it seems the TICKR is one of these devices, which are very picky about how an app attempts a connection.
I have an update ready that I'll push to Google Play this week: It includes an improved bluetooth connection method. Please retry once you've got the update.

**Comment by svenmeier** [comment]
Version 4.9 has an improved bluetooth implementation.
