### ISSUE TITLE
Question about google fit integration

### ISSUE THREAD

**Issue by mokuteki** [svenmeier/coxswain#73]
Useful app, thank you so much.  

I realize the google fit integration is in beta, but was trying to use it and wondering if there is any documentation on it.  I've see the link next to each "workout" that indicates the export to google fit.  After selecting I get a toast that says that it was exported.  But wondering if I am not doing something corrected (I do see the evaluate check box right next to it and not sure if that is related or not).  

Thanks so much

**Comment by svenmeier** [comment]
Hi,

the 'evaluate' checkbox decides whether a workout is calculated for the the performance tab, it doesn't have anything to do with export and/or Google fit.

I can't remember exactly how exporting to Google Fit worked out for me:
Coxswain uses the Google Fit API to report your workout to Google, but in my experience there were always some data missing.

Please check what data arrives in Google Fit and report back your findings.

**Comment by Gus-Fring** [comment]
Hi, seems like no response from OP.

I just tried to export some workout data to Google Fit, it opens the Google account access screen. When I allow the demanded access, the window disappears without confirmation that the data was exported - and I cannot see any data from Coxswain in Google Fit. When checking in my Google account, I cannot find Coxswain under the Apps with access into my account. When I try to export another workout (or the same workout again), the access rights box pops up again....

Something doesn't work

**Comment by Gus-Fring** [comment]
Update: suddenly the export seems to work. I see my workouts now in the Google Fit journal, however only on the very device where Coxswain runs (which is probably a Google problem).

**Comment by svenmeier** [comment]
Thanks @Gus-Fring for trying. To me Google fit doesn't give the impression of working reliably. If anyway knows an open-source program that offers successful integration with it, please let me know and I'll take another look.

**Comment by Gus-Fring** [comment]
You are probably correct, I am using Google Fit on two devices (same G account) and it doesn't even synchronise the journal. What a waste of time.

**Comment by svenmeier** [comment]
Google Fit integration was improved. Please open a new issue if you have further problems.
