### ISSUE TITLE
Check for permissions when enabling HR-sensor

### ISSUE THREAD

**Issue by elektronaut69** [svenmeier/coxswain#77]
It took me some time to find out, that I have to grant permission to access body-sensors for my HR-sensor to work. Can you add a check for permissions when using a HR-sensor is enabled?

Cheers,

Volker

**Comment by svenmeier** [comment]
Coxswain does check for permissions before accessing the sensors, your phone should ask you whether you want to grant that permission automatically.

Did you have to do this explicitly in the App permissions? What Android version and device?

**Comment by svenmeier** [comment]
Hm, just tried it out here and I get a dialog asking for the permission.

Could you please revoke the permission for the App and try again?

Which Android version please?

**Comment by elektronaut69** [comment]
Hi Sven,

There is no permissions dialog on my phone. Android Version is 8.1.0


Sven Meier <notifications@github.com> schrieb am Di., 31. Juli 2018, 09:59:

**Comment by svenmeier** [comment]
What happens with other permissions?

Please try exporting a workout to a file, a permission dialog should pop up, asking you whether you're fine with Coxswain writing to storage.

**Comment by elektronaut69** [comment]
When I remove the file permission, Coxswain is asking for the file
permission on export.

Sven Meier <notifications@github.com> schrieb am Di., 31. Juli 2018, 12:56:

**Comment by svenmeier** [comment]
At the moment I don't have a clue why acquiring permission for the sensor fails.
I've added a toast message for the next App version that will give us a hint (hopefully).

**Comment by Noggin21** [comment]
Hi Sven, great app BTW. Although I don't get HR data from my Wahoo BlueHR chest strap (an error banner appears ~30s into the workout). Other data fields from my Waterrow S4, are populated fine, and it exports OK. I also got no body sensor permissions pop-up along with the location request, but I think I fixed this manually. I'm using an Honor 8x running Android 8.1.0

**Comment by svenmeier** [comment]
@noggin21 Coxswain doesn't need body sensor permission to read your heartrate over Bluetooth.

Does your HR strap work fine with other apps?

**Comment by Noggin21** [comment]
It's always worked fine with the Wahoo app, although this app has a pairing dialog. In desparation I loaded another app, SmartRow, this app found the monitor straight away, fortunately now Coxswain also finds the monitor so this now seems sorted. However, I don't seem to be able to import the activity data into Garmin connect  (it fails right at the end with an upload error), I'm using a shared tcx file via Google drive. It also doesn't look as though I'm alone with this issue looking at the Garmin support site.

**Comment by svenmeier** [comment]
Regretfully Garmin's support isn't very helpful with these issues.

Please open a new issue if the Bluetooth stops working again for you.

**Comment by svenmeier** [comment]
@elektronaout69 Perhaps I misunderstood you: 

What sort of body sensor are you using?

**Comment by elektronaut69** [comment]
I was using a Polar Bluetooth Sensor.  I do know which exactly and I cannot
check which exactly, as I'm not at home at the moment. Lately I'm using an
ANT+ sensor with the built-in receiver add-on.



Am Do., 17. Jan. 2019, 06:01 hat Sven Meier <notifications@github.com>
geschrieben:

**Comment by svenmeier** [comment]
So my bad, I've got this mixed up:
Coxswain asks for Bluetooth permissions to connect to bluetooth devices, and it asks for Body_Sensors permission to connect to an *on-device* body sensor.

Note that these are two completely different things, and to my knowledge it should not be necessary to request for body sensor permission just to read from a bluetooth device - even it *is* a 'body sensor', Android shoudln't care nor know about that.

Would be great if you could repeat your findings, i.e. try reading via bluetooth *without* and *with* body sensor permission.

**Comment by svenmeier** [comment]
Please open a new issue if the problem persists with 6.1
