### ISSUE TITLE
Lower steps of strokes to 5 in training-programm editor

### ISSUE THREAD

**Issue by elektronaut69** [svenmeier/coxswain#78]
Can you lower the steps of the strokes counter from 10  to 5 in the program editor? I'd like to do short power-stroke segments with 15 strokes each. 

Cheers,

Volker

P.S. Das war vorerst der letzte Wunsch, versprochen. 😉

**Comment by svenmeier** [comment]
Step count 5, 10 and 15 will be possible in the upcoming Coxswain version.
