### ISSUE TITLE
Display update during workout

### ISSUE THREAD

**Issue by welloilbeefoct** [svenmeier/coxswain#80]
Hi,

I'm really enjoying using the app but have an issue where the display will only update with progressively longer intervals. Towards the end of a 10k it's only updating every 3-4 minutes; as you can imagine this proves very difficult to maintain pace etc.

It didn't used to do this so not sure if I have inadvertently changed a setting. The font is grey in clour but I'm sure it used to be black. I'm using Android. Thanks :)

**Comment by svenmeier** [comment]
Hi, did you receive the 5.5 update already?

**Comment by welloilbeefoct** [comment]
Hi, Yes using 5.5

**Comment by svenmeier** [comment]
Please retry with 5.6

**Comment by svenmeier** [comment]
Got confirmation from another user that 5.6 fixed the lag issues.
