### ISSUE TITLE
Power output?

### ISSUE THREAD

**Issue by apholt** [svenmeier/coxswain#82]
Hi svenmeier,

Great app. I have my BLE HRM working and getting great workout data. Would it be possible to export the power output of the row in the .tcx file? I have no concept of how much work I am doing in terms of m/s or mi/500m since the WR is known to be widely inaccurate. 

Thanks for all the hard work!

**Comment by svenmeier** [comment]
Just to clarify: By power you mean what the S4 reports as intensity in watts (kcal)?

**Comment by TbsJah** [comment]
Intensity would be great

**Comment by svenmeier** [comment]
The next version will record power (watts) from S4 and export in into TCX.

We'll see how accurate that is.

**Comment by apholt** [comment]
Much appreciated! Thanks, svenmeier!

**Comment by TbsJah** [comment]
Is there any news about this feature?

**Comment by svenmeier** [comment]
I've released 5.7 with support for power recording.

Note the my S4 reports slightly different power readings than it is displaying actually.
