### ISSUE TITLE
display duration longer than 1 hour

### ISSUE THREAD

**Issue by Jo11n** [svenmeier/coxswain#83]
For durations longer than 1:00:00, Coxswain displays only the last four digits at the moment. Not the biggest issue, but the expected behavior would be to show the hour as well. Thanks!

**Comment by svenmeier** [comment]
Well, that is done by purpose: With a leading hour 1:00:00 the value is too broad for most phone displays.

I'll change it to show up to 99 minutes, so hard-working rowers like you know where you're at.

**Comment by Jo11n** [comment]
maybe the current behavior is better then. Aiming for marathon distance. 99 min won't be enough I'm afraid :-O
