### ISSUE TITLE
How to export all workouts and import on new phone

### ISSUE THREAD

**Issue by kosli** [svenmeier/coxswain#84]
I haven't had the automatic export enabled before, but would like to export all my workouts and import them on my new phone (into Coxswain). What is the easiest way? I only see the option to export every single workout one by one? Thanks for this great app.

**Comment by svenmeier** [comment]
Do you have App backups enabled on your phone/Google account? Then your data should be migrated automatically to your new device. 
Alternatively you can use a backup software like titanium backup.

I was planning to an a bulk export to Coxswain, but haven't had time to program it yet.

**Comment by kosli** [comment]
No, I explictely do not want to have the data backed up to Google.
On the old device I had used titanium backup, but as the new phone is not rootable I cannot import the data back from titanium. But I may try to get the data out by adb backup. 
Thanks for the information

**Comment by svenmeier** [comment]
I applaud your efforts to keep your data for yourself.

With adb backup it should work: https://androidquest.wordpress.com/2014/09/18/backup-applications-on-android-phone-with-adb/
