### ISSUE TITLE
Weird behavior

### ISSUE THREAD

**Issue by gogolo2** [svenmeier/coxswain#85]
A lot of times now when I started a training the training view (time, tempo heart rate etc.) suddenly disapears. I seems to be in the background, sometimes it continues when I restart the training. But sometimes also not and coxswain crashes even. I have the impression it could occur when the heart rate sensor (polar) reconnects which happens sometimes. If this is the issue could coxswain be made more insensible to hr drop outs? Im running coxswain on oreo. thx.

**Comment by svenmeier** [comment]
So does this happens at all when configure Coxswain to use the S4 heart rate sensor?
(Although you probably don't have it.)

**Comment by svenmeier** [comment]
Please retry with the upcoming 6.1 and report back if the problem persists.

**Comment by gogolo2** [comment]
Sorry for the late reply, I think it was a faulty usb otg cable, with a new I didn't have these events.
