### ISSUE TITLE
Bluetooth LE connection

### ISSUE THREAD

**Issue by f-bader** [svenmeier/coxswain#86]
Hi @svenmeier , thank you for this great app. It's perfect for keeping track of the use of the WaterRower.
The only feature I could not get working is the Bluetooth LE connection to my heartbeat monitor.
I already tried to connect another app to the HR sensor, right before using Coxswain but with no luck so far. Coxwain does not identify the HR sensor and I cannot find a possibility to select it either.

Does anybody have any tips on this matter?

Phone: Essential PH-1
HR Monitor: Berry King Heartrate Sensor

On an unrelated note: The version in the Play Store is already on 6.0. Is there some change in license it's not published on GitHub anymore?

**Comment by svenmeier** [comment]
> 6.0 is not published on GitHub
Sorry, my bad, I forgot it. I pushed a new release just now.

>Bluetooth LE
I'm using a Berry King too and works quite reliably. 
>tried to connect another app to the HR sensor, right before using Coxswain but with no luck so far.
Do you mean the other app cannot connect either?
Once you've configured Coxswain to read heart-rate data from bluetooth, the app should automatically connect to your Berry King once you select a workout.
Do you see any toasts showing up regarding bluetooth problems?

(https://developer.android.com/guide/topics/ui/notifiers/toasts)

**Comment by f-bader** [comment]
>Do you mean the other app cannot connect either?
No with the other app it worked just fine

I always get toasts along the line "Suche nach Puls über Bluetooth" and "Kein Puls über Bluetooth gefunden". In the bluetooth menu of android there was even a bluetooth device named "heart rate sensor". Maybe I have to wait a little bit longer after I start the app, or should it work nonetheless?

**Comment by svenmeier** [comment]
Upon starting of a workout, Coxswain immediately scans for BLE devices and uses the first one that supports heart rate measurements. This happens between those two messages, it doesn't help waiting any longer :/,

Are you able to send my the log output of the application? Do you know how to access logcat on your device?

**Comment by f-bader** [comment]
Now I'm a bit embarrassed.
Today I tried again and the sensor was paired almost immediately and worked great the whole session.
Thanks for your effort and help.

**Comment by f-bader** [comment]
Sorry for having to reopen this issue but today I could not connect again.
I checked the logcat messages and stumbled upon this:

```
08-09 14:03:09.263 25455 25455 D coxswain: bluetooth scanned 40:B8:9A:3E:01:NN
08-09 14:03:09.263 25455 25455 D coxswain: bluetooth unscan
08-09 14:03:09.263 25455 25455 D BluetoothAdapter: stopLeScan()
08-09 14:03:09.264 25455 25455 D BluetoothAdapter: isLeEnabled(): ON
08-09 14:03:09.265 25455 25455 D coxswain: bluetooth connecting 40:B8:9A:3E:01:NN
08-09 14:03:09.267 25455 25455 D BluetoothGatt: connect() - device: 40:B8:9A:3E:01:NN, auto: false
08-09 14:03:09.267 25455 25455 D BluetoothGatt: registerApp()
08-09 14:03:09.267 25455 25455 D BluetoothGatt: registerApp() - UUID=6ddba53f-0ebc-479c-8990-af1b9c2c87d4
08-09 14:03:09.268  2015  2528 I bt_stack: [INFO:gatt_api.cc(948)] GATT_Register d37e496f-df2d-a55a-acd7-cd0da7da8d9b
08-09 14:03:09.268  2015  2528 I bt_stack: [INFO:gatt_api.cc(968)] allocated gatt_if=7
08-09 14:03:09.269 25455 25467 D BluetoothGatt: onClientRegistered() - status=0 clientIf=7
08-09 14:03:09.273  2015  2127 D bt_btif_config: btif_get_address_type: Device [40:B8:9A:3E:01:NN] address type 0
08-09 14:03:09.273  2015  2127 D bt_btif_config: btif_get_device_type: Device [40:B8:9A:3E:01:NN] type 3
08-09 14:03:09.273  2015  2528 I bt_stack: [INFO:gatt_api.cc(1109)] GATT_Connectgatt_if=7 40:B8:9A:3E:01:NN
08-09 14:03:09.278 10394 25477 I TTS.ControllerWrapper: Done initializing de-de-x-nfh-lstm-embedded
08-09 14:03:10.275  2315  2531 D WCNSS_FILTER: wcnss_release_wakelock
08-09 14:03:11.107  1572  1835 E Diag_Lib: [IMS_FATAL]| 1835 |ims_qmi_register_client : Failed
08-09 14:03:11.109  1572  1835 E Diag_Lib: [IMS_FATAL]| 1835 |ims_qmi_register_client : Failed
08-09 14:03:11.213  2499 21540 W ChimeraUtils: Non Chimera context
08-09 14:03:11.213  2499 21540 W ChimeraUtils: Non Chimera context
08-09 14:03:11.245  2315  2315 D WCNSS_FILTER: wcnss_acquire_wakelock
08-09 14:03:11.247  2015  2528 W bt_sdp  : SDP - Rcvd conn cnf with error: 0x4  CID 0x43
08-09 14:03:11.248  2015  2545 E bt_btif_sock_rfcomm: find_rfc_slot_by_id unable to find RFCOMM slot id: 1258
08-09 14:03:11.255  2499  4453 W WearableConn: Failed to connect, error: read failed, socket might closed or timeout, read ret: -1
```

It finds a BLE device (my "Smart" TV) on MAC 40:B8:9A:3E:01:NN (removed last to digits) and tries to connect. This fails as expected.
Than it tries other BLE devices but never the heart rate sensor and most likely times out before trying it.
3D:3F:FC:3F:17:NN
4C:65:A8:D9:9D:NN
4C:65:A8:D9:A3:NN
3F:9B:A7:1A:AD:NN
4C:65:A8:D9:A3:NN

Heart rate sensor:
f4:d1:4a:c8:b4:NN

It would be great if you could implement a scan and selection and force the BLE connection to the device specified by the user.

For further analysis I pasted the complete log [here](https://pastebin.com/WvWUEb1b)
It will be removed in one week

If I can help testing I would be more than glad to do so.

**Comment by svenmeier** [comment]
Thanks that's the information I was looking for.

Wow, you have a lot of running Bluetooth devices around you. I'll take a look.at your log on Sunday.

Many thanks
Sven

**Comment by svenmeier** [comment]
You're right, trying to connect to 3D:3F:FC:3F:17:NN takes 30 seconds, the next try with 3F:9B:A7:1A:AD:N doesn't successfully connect before 25 seconds have passed. Thus the overall timeout of 60 seconds is exceeded.

**Comment by svenmeier** [comment]
Upcoming version will allow the user to choose the bluetooth device.
