### ISSUE TITLE
Feature Request: Custom filename or keyword

### ISSUE THREAD

**Issue by f-bader** [svenmeier/coxswain#87]
Hi,

It would be great if out was possible to add some custom keyword to the filename.
I use SyncMyTracks to import the training files to Garmin. The app could change the activity automatically to something custom if part of the filename matches the activity (e.g. rowing).

Would make my life a bit easier not to have adjust the activity type manually after a sync.

Best, Fabian

**Comment by svenmeier** [comment]
Well, the name of the workout is included in the filename. Have you tried to rename your workouts accordingly?

**Comment by f-bader** [comment]
Good point. I will give it a try.
