### ISSUE TITLE
BLE Connection with WaterRower ComModule

### ISSUE THREAD

**Issue by WaldoPepper** [svenmeier/coxswain#89]
Hi, are there any plans to connect with the "WaterRower Com Module" Bluetooth accessory for the S4? Getting rid of the OTG and the cable would be kind of nice... ;-)

**Comment by svenmeier** [comment]
I wasn't aware of that accessory, thanks! Would be nice to no longer fiddle with a cable.

**Comment by svenmeier** [comment]
The next version will support Bluetooth connection to the WaterRower ComModule.

**Comment by tamasvajk** [comment]
@svenmeier Do you know if the WaterRower ComModule acts as a GATT server that can be understood by other commercial products? Are the rowing service/characteristics specified in the standard, and used by other products? I have a Polar V800 watch which has an indoor rower sports profile, but I'm unsure if it can be paired with the ComModule.

**Comment by svenmeier** [comment]
The ComModule supports the fitness machine standard:

https://www.bluetooth.com/wp-content/uploads/Sitecore-Media-Library/Gatt/Xml/Services/org.bluetooth.service.fitness_machine.xml
