### ISSUE TITLE
Software manual?

### ISSUE THREAD

**Issue by Gus-Fring** [svenmeier/coxswain#90]
Hi Sven, I cannot find a manual - does it exist?

What I am looking for is a description of the storage location and export settings. I would like to store my data in a central external location in my network, however cannot find where I can edit the location? Similar for export, I can export each workout, but I struggle to see where the info is written?

**Comment by dt192** [comment]
On my phone the exports go to 'internal storage > coxwain'.

**Comment by svenmeier** [comment]
In the Coxswain settings you can switch the database to be stored in in an external location instead in the App data.
Both - database and exports - are stored in a folder "/coswain" on your phone's internal storage.

**Comment by Gus-Fring** [comment]
Hi Sven, my point was how about letting the user define the path for the external storage? Then I can gather my data on my Onedrive. Now I have to export them one by one.
Also don't understand what checking the automatic export changes, where to and in which format is the automatic export executed?

**Comment by Gus-Fring** [comment]
One more question: even if I copy .tcx files from another Coxswain app to my /coxswain folder, I still need to import the sessions one by one in order to see them under the workout tab?
