### ISSUE TITLE
6.2 app crash 

### ISSUE THREAD

**Issue by juesteiger** [svenmeier/coxswain#93]
app crash after plug in usb cable and start a training. i downloaded 6.1 from github and installed it, works without issues again

thxs for this great app, hopefully you can find the rc for the crash

**Comment by TbsJah** [comment]
Same for me

**Comment by svenmeier** [comment]
Yes, there seems to be a problem with some devices. I'm working on it.

**Comment by juesteiger** [comment]
thxs! Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Sven Meier <notifications@github.com> Datum: 21.10.19  09:37  (GMT+01:00) An: svenmeier/coxswain <coxswain@noreply.github.com> Cc: juesteiger <jue.steiger@gmail.com>, Author <author@noreply.github.com> Betreff: Re: [svenmeier/coxswain] 6.2 app crash  (#93) Yes, there seems to be a problem with some devices. I'm working on it.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/svenmeier/coxswain/issues/93?email_source=notifications\u0026email_token=ANQ3R4NAZR7SEDFQKZ6KAFDQPVL5BA5CNFSM4JCJ7M3KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBZLMYQ#issuecomment-544388706",
"url": "https://github.com/svenmeier/coxswain/issues/93?email_source=notifications\u0026email_token=ANQ3R4NAZR7SEDFQKZ6KAFDQPVL5BA5CNFSM4JCJ7M3KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBZLMYQ#issuecomment-544388706",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by charles-0** [comment]
Thank you Sven for your quick response to my email.
I'd like to report that everything is good with Github APK v6.1.  The only bad thing is I lost all the past data.  However, when I reinstall v6.2 from Google Play store, all the data is there again.

Where is the data stored?  Perhaps I can simply copy it over to v6.1?  Is it possible?

**Comment by altecfx** [comment]
As per above, is there a way to roll back to 6.1 and retain data until issue fixed?

Love this app btw.

**Comment by svenmeier** [comment]
All effected by this bug, please report back whether
- you are using a Bluetooth heart rate monitor,
- you have checked the "adjust energy" setting
- changing any/both of these settings circumvents the problem.

Thanks

**Comment by Syrill** [comment]
Regarding your questions:

- no bluetooth heart rate monitor
- "adjust energy" was checked on my 6.2 installation
- as far as I remember, no

**Comment by charles-0** [comment]
No Bluetooth Heartrate monitor.  Only Ant+.

"Adjust energy" setting was checked on v6.2.
When checked, the following occurs:
1) The distance counter would be counting up from 0.  Normally this should be a countdown.
2) After approx. 10 meters is reached, the message "Rower was reset" message would appear.
3) The S4 monitor would also reset (same as if I held down the power for 2 sec)
4) The Speed indicator is always 0.

"Adjust energy" setting UN-checked on v6.2
1) The distance counter is doing a countdown (normal)
2) I was able to do a test row up to 400 meters with no reset message.
3) The speed indicator is still registering 0 speed.

Both of the above setting were conducted using Ant+ and Waterrower as sensors.  I don't have a Bluetooth HR monitor.  But I did choose it, and ran the same test above with same result.  So I don't think these sensor settings would affect the outcome.

**Comment by juesteiger** [comment]
* no bluetooth from app point of view - polar h10 is connected to the s4 (with the polar receiver available for waterrower) and the app reads heartrate from s4
* adjust energy enabled
* did not try to unset the engery setting

**Comment by svenmeier** [comment]
Ok, it seems to be related to the "adjust energy" setting.

Please unset in 6.2 and report back.

**Comment by juesteiger** [comment]
hi, 

with unset "adjust energy" 6.2 works without crash 👍 
would be great to if you coul fix this in a future release but for now i can keep on rowing. 

thxs so far for your support and br
juergen

**Comment by svenmeier** [comment]
This is fixed with new 6.3 - sorry for this, I should have been more careful with the previous release.

**Comment by Syrill** [comment]
6.3 works just fine! :)
Thank you for the fast response and fix!
