### ISSUE TITLE
How to recover data from previous installations

### ISSUE THREAD

**Issue by Syrill** [svenmeier/coxswain#94]
Due to the [issues with version 6.2](https://github.com/svenmeier/coxswain/issues/93) I have lost my old training data. Is it possible to recover and re-integrate this data into my current installation of the app? And if so, how would I do it?

Thank you, I really love the app! :)

**Comment by svenmeier** [comment]
Sorry for this annoyance :/.

I'm surprised that installing a previous version should use a separate data. Please check for the new 6.3 update from the Play store and let's hope that your data shows up again.

**Comment by Syrill** [comment]
No need to be sorry, I was simply curious, if there is a way to save my training history.

I did uninstall the 6.2 version, download the version before from GitHub and my old data was gone. I did not think that I might loose data, otherwise I would have saved it elsewhere before...
The old data was probably deleted when I uninstalled the app?

**Comment by svenmeier** [comment]
It's unclear to me how Android handles this:
Yes, uninstalling an App removes all its data. But if you have Google backups enabled, the data should be recovered once you reinstall the app.
In principle Coxswain allows this, but I've never seen this work out on any device actually :(

To be honest backups on Android are a mess.
