### ISSUE TITLE
Graph scaling time intervals bug

### ISSUE THREAD

**Issue by kerr-bighealth** [svenmeier/coxswain#96]
First, thank you for providing one of the few working solutions for us WaterRower users, without having to pay $$$ for a premium solution that doesn't work very well.

I am experiencing a small bug with time display when zooming into the graph of a workout.  I'll attach a screenshot, which should show exactly the issue.  Here, notice the graph timeline progresses as:
```
0:00
0:20
1:40
1:00
1:20
2:40
2:00
2:20
```

I've seen this issue at various zoom levels, although when fully zoomed out and looking at the entire workout, the issue does not occur.

![Screenshot_20200120-130134_Coxswain](https://user-images.githubusercontent.com/51177070/72752719-93d4a880-3b88-11ea-863d-e0e2e1d87a87.jpg)

**Comment by svenmeier** [comment]
Thanks, that was a silly bug ;)

Will be fixed in next version.
