### ISSUE TITLE
Feature request: Adding an activity tag like "rowing" or "row" to .tcx filename

### ISSUE THREAD

**Issue by shiQzaL** [svenmeier/coxswain#97]
First of all - great app, I love it!

I use SyncMyTracks to synchronize my activity to other apps like Strava or Runtastic.
Can you maybe put an activity tag like "rowing" or "row" to the filename of the .tcx file which can be stored in external location (coxswain folder) or can exported to another location.

Examples:

> 2020-01-29_17-41-41_30 Minuten_**rowing**.tcx

or

> 2020-01-29_17-41-41_30 Minuten_**row**.tcx

With these tags in the filename, SyncMyTracks can automatically set the right activity in apps like Strava or Runtastic. Without any tag in the filename, it's just tagging "Other" as activity and I must edit it manually in every app.

Thank you!

**Comment by shiQzaL** [comment]
Today I recognized that it's already puts the name of the training program into the filename. So if I name a training program "30 minutes rowing", the saved and exported filename is e.g. 2020-01-29_17-41-41_30 minutes rowing.tcx

So that requested feature is already implemented and SyncMyTracks can automatically set the right training activity into other apps :)

**Comment by svenmeier** [comment]
Yes, I wanted to write that, but you found it out already. +1
