### ISSUE TITLE
60 Minuten Intervalltraining ist im Ergebnis 1 Stunde 59 Minuten.

### ISSUE THREAD

**Issue by Aldebaran911** [svenmeier/coxswain#98]
Hallo,
ich habe mir ein Intervalltraining mit 6 Mal 10 Minuten und verschiedenen Pulszielen erstellt. Heute erstmalig gerudert und nach Beendigung stehen in der Trainingsdatei 1 h 59 Minuten. Vielleicht ein Fehler im Code?   Ist so auch in Google Fit exportiert worden.
Grüße
Jens

**Comment by svenmeier** [comment]
Hi Jens,

kannst du eine TCX Datei exportieren und hier angehängen?

Danke

**Comment by Aldebaran911** [comment]
Hallo Sven,

kann ich leider nicht, da ich die vorhandene Datei im Editor geöffnet habe
und die Sekunden von 7xxx Sekunden auf 3600 geändert habe. Nach erneutem
Import passte es dann halbwegs. Jetzt steht im Ergebnis 1:00:09.
Werde voraussichtlich morgen oder übermorgen die Datei nochmals rudern.
Wenn es dann wieder sein sollte, sende ich sie Dir.

Grüsse aus Verl
Jens
PS: Ansonsten wirklich eine tolle App, vielen Dank dafür. Verstehe nicht,
daß Waterrower soetwas nicht hinbekommt und gar drei verschiedene
Softwarevarianten für USB Anschluss, Com Modul und Smart Row
verõffentlicht.

Sven Meier <notifications@github.com> schrieb am Mi., 5. Feb. 2020, 16:23:

**Comment by Aldebaran911** [comment]
Hallo Sven,

anbei die Datei von heute.

Grüsse aus Verl

Jens

**Comment by svenmeier** [comment]
Die Datei ist nicht durchgekommen (auch per Mail nicht), kannst du sie bitte hier auf dem Issue anhängen?
("Attach files by dragging & dropping...") https://github.com/svenmeier/coxswain/issues/98)

**Comment by Aldebaran911** [comment]
Also die Möglichkeit des Einfügens von Dateien finde ich nicht. Nur Bilder können hier eingefügt werden 🤔. Wo kann ich per Drag and Drop was einfügen?

**Comment by Aldebaran911** [comment]
![Screenshot_2020-02-06-10-26-11-26_790ce7c340f790b20678444fdee2bd1e](https://user-images.githubusercontent.com/60704033/73939874-a837d580-48ea-11ea-8684-7482a28f3e45.png)
![Screenshot_2020-02-05-22-14-44-99_790ce7c340f790b20678444fdee2bd1e](https://user-images.githubusercontent.com/60704033/73939892-ad952000-48ea-11ea-92a5-9ff9d57ee4b1.png)

**Comment by svenmeier** [comment]
Oh, danke, ich hatte nicht verstanden, dass die Anzeige in der App schon verkehrt ist.

Kannst du mir die TCX-Datei an sven[at]meiers.net schicken?

**Comment by svenmeier** [comment]
Oh, danke, ich hatte nicht verstanden, dass die Anzeige in der App schon verkehrt ist.

Kannst du mir die TCX-Datei an sven[at]meiers.net schicken?

**Comment by Aldebaran911** [comment]
Aber die .tcx Datei bekomme ich hier nicht hinein...

**Comment by svenmeier** [comment]
Ruderst du über USB oder Bluetooth?

**Comment by Aldebaran911** [comment]
Bluetooth

**Comment by Aldebaran911** [comment]
Habe ich geschickt

**Comment by svenmeier** [comment]
Danke, wie ich mir gedacht habe: Es wurden korrekt ~60 minuten getrackt, aber dann hat das S4 Bluetooth-Module noch eine falsche Zeit (~120 minuten) geliefert - Coxswain schreibt das nur auf.

Ich musste schon einen Workaround einbauen, da das Bluetooth-Module manchmal die falsche Zeit liefert.

**Comment by Aldebaran911** [comment]
Und kannst Du das Problem lösen?

Sven Meier <notifications@github.com> schrieb am Do., 6. Feb. 2020, 14:27:

**Comment by svenmeier** [comment]
Klar, da muss ich mir ein Workaround einfallen lassen.

Kannst du mal Test-weise dein Training auf 6x9 Minuten ändern? Ich vermute dann tritt das Problem nicht auf.

**Comment by Aldebaran911** [comment]
Ja mache ich🥴. Wird wahrscheinlich erst am Wochenende.

Sven Meier <notifications@github.com> schrieb am Do., 6. Feb. 2020, 17:26:

**Comment by Aldebaran911** [comment]
Hallo Sven,

heute mit 6x9 min war alles OK. Wenn Du die Datei trotzdem haben möchtest,
dann gib mir Bescheid.

Grüße
Jens

Jens A. <jens.adam911@gmail.com> schrieb am Do., 6. Feb. 2020, 18:27:

**Comment by svenmeier** [comment]
In Version 6.8 habe ich den Workaround erweitert. Hoffentlich fixed das auch das Problem bei der Stundengrenze.

**Comment by Aldebaran911** [comment]
Super, vielen Dank.
Probiere ich spätestens übermorgen aus.

Sven Meier <notifications@github.com> schrieb am Di., 11. Feb. 2020, 20:36:

**Comment by Aldebaran911** [comment]
Hallo Sven,
leider funktioniert es doch noch nicht.
Heutige Datei anbei.
Oder muss ich das Intervalltraining zunächst neu erstellen?
Grüsse
Jens

Jens A. <jens.adam911@gmail.com> schrieb am Mi., 12. Feb. 2020, 09:47:

**Comment by svenmeier** [comment]
Nein, du musst nichts neu erstellen.

Ich denke, ich werde auch mal über eine Stunden rudern, um das Problem nachvollziehen zu können.

**Comment by vonloxley** [comment]
Das ist, für einen Softwareentwickler, ein erstaunlicher Einsatz!

**Comment by svenmeier** [comment]
Stimmt, bei 60 Minuten rudern komme ich wirklich mal ins Schwitzen ;-)

**Comment by Aldebaran911** [comment]
Ja, der Einsatz ist grandios. Hoffentlich kauft Waterrower Dir die Software
eines Tages für 1,5 Mio. ab....  . Ob man 6 Minuten mit maximaler
Intensität oder 60 Minuten mit angepasster Intensität rudert, die Suppe
läuft immer. Mir ist noch aufgefallen, das nach Export und erneutem Import
der TCX Datei die Kraftkurve im Diagramm  auf null steht.

Sven Meier <notifications@github.com> schrieb am Do., 13. Feb. 2020, 13:12:

**Comment by svenmeier** [comment]
Ok, 60 Minuten später kann ich den Fehler bestätigen.

Die Zeit vom Comm module springt bei 60 Minuten erst kurz auf 159 Minuten (7140 Sekunden).

Da muss ich den Workaround noch ein bisschen anpassen. Ich werde das Problem auch mit den Entwicklern von Waterrower besprechen.

**Comment by Aldebaran911** [comment]
Ja schön! lch habe jetzt immer die Datei im Editor geöffnet, die Sekunden
auf 3600 gesetzt und dann in Coxswain importiert. Die Zeit wurde in Deiner
App dann immer mit 1:00:09 angezeigt. Nur wie bereits geschrieben geht
dabei die Kraftkurve im Diagramm verloren.

Sven Meier <notifications@github.com> schrieb am Do., 13. Feb. 2020, 21:48:

**Comment by fatman3** [comment]
Hallo,
Ich finde die App wirklich super! Hatte auch das Problem, dass beim Import der TCX Datei die Kraftkurve nicht mehr eingelesen wird.
Ich habe den Sourcecode durchstöbert und bin dann daruaf gekommen, dass in "garmin.TCX2Workout.java" der Wert nicht eingelesen wird. Man kann dem einfach abhelfen, indem man nach Zeile 149 folgendes einfügt:
`				snapshot.power.set(Integer.parseInt(navigator.getText("Watts")));
`

![grafik](https://user-images.githubusercontent.com/64635423/80862209-7331e980-8c73-11ea-843a-ede7221f85ff.png)

**Comment by svenmeier** [comment]
Hi @fatman3 , danke das Thema hatte ich total vergessen.

Du hast recht, dein Fix sorgt dafür, dass die Kraft auch wieder eingelesen wird.
Ich werde das für die nächste Version übernehmen.

Das ursprüngliche Problem mit der Zeitmessung nach einer Stunde ist bereit durch einen Workaround behoben.

Sven
